/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-angular:src/main/java/repository/EntityRepository.java.e.vm
 */
package com.sadetec.repository;

import java.util.List;

import org.springframework.data.domain.Example;
import org.springframework.data.domain.ExampleMatcher;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.jpa.repository.JpaRepository;

import com.sadetec.model.Category;
import com.sadetec.model.Category_;

public interface CategoryRepository extends JpaRepository<Category, Integer> {

	List<Category> findByHasChildCategoryAndProcFlag(Boolean hasChild, Boolean procFlag);
	
	List<Category> findByHasChildCategoryAndProcByIsNull(Boolean hasChild);
	
	Category findById(String categoryCode);
	
    default List<Category> complete(String query, int maxResults) {
        Category probe = new Category();
        probe.setCategoryName(query);

        ExampleMatcher matcher = ExampleMatcher.matching() //
                .withMatcher(Category_.categoryName.getName(), match -> match.ignoreCase().startsWith());

        Page<Category> page = findAll(Example.of(probe, matcher), new PageRequest(0, maxResults));
        return page.getContent();
    }
}