/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-angular:src/main/java/repository/EntityRepository.java.e.vm
 */
package com.sadetec.repository;

import java.util.List;

import org.springframework.data.domain.Example;
import org.springframework.data.domain.ExampleMatcher;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.domain.Pageable;
import org.springframework.data.jpa.repository.JpaRepository;

import com.sadetec.model.MailMessage;
import com.sadetec.model.MailMessage_;

public interface MailMessageRepository extends JpaRepository<MailMessage, Integer> {

    default List<MailMessage> complete(String query, int maxResults) {
        MailMessage probe = new MailMessage();
        probe.setWriteUid(query);

        ExampleMatcher matcher = ExampleMatcher.matching() //
                .withMatcher(MailMessage_.writeUid.getName(), match -> match.ignoreCase().startsWith());

        Page<MailMessage> page = findAll(Example.of(probe, matcher), new PageRequest(0, maxResults));
        return page.getContent();
    }
    
    Page<MailMessage> findByResId(Integer resId, Pageable pageable);
    
    MailMessage findById(Integer id);
}