/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-angular:src/main/java/repository/EntityRepository.java.e.vm
 */
package com.sadetec.repository;

import java.util.List;

import org.springframework.data.domain.Example;
import org.springframework.data.domain.ExampleMatcher;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.jpa.repository.JpaRepository;

import com.sadetec.model.ProductSupplierinfo;
import com.sadetec.model.ProductSupplierinfo_;

public interface ProductSupplierinfoRepository extends JpaRepository<ProductSupplierinfo, Integer> {

    default List<ProductSupplierinfo> complete(String query, int maxResults) {
        ProductSupplierinfo probe = new ProductSupplierinfo();
        probe.setCreateUid(query);

        ExampleMatcher matcher = ExampleMatcher.matching() //
                .withMatcher(ProductSupplierinfo_.createUid.getName(), match -> match.ignoreCase().startsWith());

        Page<ProductSupplierinfo> page = findAll(Example.of(probe, matcher), new PageRequest(0, maxResults));
        return page.getContent();
    }
}