/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-angular:src/main/java/repository/EntityRepository.java.e.vm
 */
package com.sadetec.repository;

import java.util.List;

import org.springframework.data.domain.Example;
import org.springframework.data.domain.ExampleMatcher;
import org.springframework.data.domain.Page;
import org.springframework.data.domain.PageRequest;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.data.jpa.repository.Query;

import com.sadetec.model.QuotationLog;
import com.sadetec.model.QuotationLogStatistics;
import com.sadetec.model.QuotationLog_;

public interface QuotationLogRepository extends JpaRepository<QuotationLog, Integer> {

    default List<QuotationLog> complete(String query, int maxResults) {
        QuotationLog probe = new QuotationLog();
        probe.setName(query);

        ExampleMatcher matcher = ExampleMatcher.matching() //
                .withMatcher(QuotationLog_.name.getName(), match -> match.ignoreCase().startsWith());

        Page<QuotationLog> page = findAll(Example.of(probe, matcher), new PageRequest(0, maxResults));
        return page.getContent();
    }

    @Query(value = "select new com.sadetec.model.QuotationLogStatistics(ql.atProductCode, ql.atProductName, ql.miProductCode, ql.miProductName, ql.name, count(ql)) from QuotationLog ql group by ql.atProductCode order by count(ql) desc")
	List<QuotationLogStatistics> findTopQuotaionProduct();
    
    @Query(value = "select new com.sadetec.model.QuotationLogStatistics(ql.name, count(ql)) from QuotationLog ql group by ql.name order by count(ql) desc")
	List<QuotationLogStatistics> findTopName();
}