/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-angular:src/main/java/domain/Entity.java.e.vm
 */
package com.sadetec.model;

import static javax.persistence.GenerationType.IDENTITY;

import java.io.Serializable;
import java.util.logging.Logger;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.Size;

import org.hibernate.validator.constraints.NotEmpty;

import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;

@Entity
@Table(name = "category_spec")
public class CategorySpec implements Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = Logger.getLogger(CategorySpec.class.getName());

    // Raw attributes
    private Integer id;
    private String categoryCode;
    private String key;
    private String title;
    private String unit;
    private String illustrationType;
    private String categorySpecNo;
    private String propertyCode;
    private String aryChoiceName;
    private String aryChoiceCode;
    private String valueType;
    private String extraSpec;
    private String noticeString;
    private String hasParamSpec;
    private String useFlag;
    private String groupingStep;
    private String displayPattern;
    private String isSpecInch;
    private String similarFlag;
    private String groupTitle;
    private String groupNoticeString;
    private String groupIndex;
    private String isParent;

    public String entityClassName() {
        return CategorySpec.class.getSimpleName();
    }

    // -- [id] ------------------------

    @Column(name = "id", precision = 10)
    @GeneratedValue(strategy = IDENTITY)
    @Id
    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public CategorySpec id(Integer id) {
        setId(id);
        return this;
    }

    @Transient
    public boolean isIdSet() {
        return id != null;
    }
    // -- [categoryCode] ------------------------

    @NotEmpty
    @Size(max = 128)
    @Column(name = "category_code", nullable = false, length = 128)
    public String getCategoryCode() {
        return categoryCode;
    }

    public void setCategoryCode(String categoryCode) {
        this.categoryCode = categoryCode;
    }

    public CategorySpec categoryCode(String categoryCode) {
        setCategoryCode(categoryCode);
        return this;
    }
    // -- [key] ------------------------

    @NotEmpty
    @Size(max = 64)
    @Column(name = "`key`", nullable = false, length = 64)
    public String getKey() {
        return key;
    }

    public void setKey(String key) {
        this.key = key;
    }

    public CategorySpec key(String key) {
        setKey(key);
        return this;
    }
    // -- [title] ------------------------

    @Size(max = 256)
    @Column(name = "title", length = 256)
    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public CategorySpec title(String title) {
        setTitle(title);
        return this;
    }
    // -- [unit] ------------------------

    @Size(max = 512)
    @Column(name = "unit", length = 512)
    public String getUnit() {
        return unit;
    }

    public void setUnit(String unit) {
        this.unit = unit;
    }

    public CategorySpec unit(String unit) {
        setUnit(unit);
        return this;
    }
    // -- [illustrationType] ------------------------

    @Size(max = 256)
    @Column(name = "illustration_type", length = 256)
    public String getIllustrationType() {
        return illustrationType;
    }

    public void setIllustrationType(String illustrationType) {
        this.illustrationType = illustrationType;
    }

    public CategorySpec illustrationType(String illustrationType) {
        setIllustrationType(illustrationType);
        return this;
    }
    // -- [categorySpecNo] ------------------------

    @Size(max = 256)
    @Column(name = "category_spec_no", length = 256)
    public String getCategorySpecNo() {
        return categorySpecNo;
    }

    public void setCategorySpecNo(String categorySpecNo) {
        this.categorySpecNo = categorySpecNo;
    }

    public CategorySpec categorySpecNo(String categorySpecNo) {
        setCategorySpecNo(categorySpecNo);
        return this;
    }
    // -- [propertyCode] ------------------------

    @Size(max = 512)
    @Column(name = "property_code", length = 512)
    public String getPropertyCode() {
        return propertyCode;
    }

    public void setPropertyCode(String propertyCode) {
        this.propertyCode = propertyCode;
    }

    public CategorySpec propertyCode(String propertyCode) {
        setPropertyCode(propertyCode);
        return this;
    }
    // -- [aryChoiceName] ------------------------

    @Size(max = 65535)
    @Column(name = "ary_choice_name", length = 65535)
    public String getAryChoiceName() {
        return aryChoiceName;
    }

    public void setAryChoiceName(String aryChoiceName) {
        this.aryChoiceName = aryChoiceName;
    }

    public CategorySpec aryChoiceName(String aryChoiceName) {
        setAryChoiceName(aryChoiceName);
        return this;
    }
    // -- [aryChoiceCode] ------------------------

    @Size(max = 65535)
    @Column(name = "ary_choice_code", length = 65535)
    public String getAryChoiceCode() {
        return aryChoiceCode;
    }

    public void setAryChoiceCode(String aryChoiceCode) {
        this.aryChoiceCode = aryChoiceCode;
    }

    public CategorySpec aryChoiceCode(String aryChoiceCode) {
        setAryChoiceCode(aryChoiceCode);
        return this;
    }
    // -- [valueType] ------------------------

    @Size(max = 256)
    @Column(name = "value_type", length = 256)
    public String getValueType() {
        return valueType;
    }

    public void setValueType(String valueType) {
        this.valueType = valueType;
    }

    public CategorySpec valueType(String valueType) {
        setValueType(valueType);
        return this;
    }
    // -- [extraSpec] ------------------------

    @Size(max = 256)
    @Column(name = "extra_spec", length = 256)
    public String getExtraSpec() {
        return extraSpec;
    }

    public void setExtraSpec(String extraSpec) {
        this.extraSpec = extraSpec;
    }

    public CategorySpec extraSpec(String extraSpec) {
        setExtraSpec(extraSpec);
        return this;
    }
    // -- [noticeString] ------------------------

    @Size(max = 256)
    @Column(name = "notice_string", length = 256)
    public String getNoticeString() {
        return noticeString;
    }

    public void setNoticeString(String noticeString) {
        this.noticeString = noticeString;
    }

    public CategorySpec noticeString(String noticeString) {
        setNoticeString(noticeString);
        return this;
    }
    // -- [hasParamSpec] ------------------------

    @Size(max = 256)
    @Column(name = "has_param_spec", length = 256)
    public String getHasParamSpec() {
        return hasParamSpec;
    }

    public void setHasParamSpec(String hasParamSpec) {
        this.hasParamSpec = hasParamSpec;
    }

    public CategorySpec hasParamSpec(String hasParamSpec) {
        setHasParamSpec(hasParamSpec);
        return this;
    }
    // -- [useFlag] ------------------------

    @Size(max = 256)
    @Column(name = "use_flag", length = 256)
    public String getUseFlag() {
        return useFlag;
    }

    public void setUseFlag(String useFlag) {
        this.useFlag = useFlag;
    }

    public CategorySpec useFlag(String useFlag) {
        setUseFlag(useFlag);
        return this;
    }
    // -- [groupingStep] ------------------------

    @Size(max = 256)
    @Column(name = "grouping_step", length = 256)
    public String getGroupingStep() {
        return groupingStep;
    }

    public void setGroupingStep(String groupingStep) {
        this.groupingStep = groupingStep;
    }

    public CategorySpec groupingStep(String groupingStep) {
        setGroupingStep(groupingStep);
        return this;
    }
    // -- [displayPattern] ------------------------

    @Size(max = 256)
    @Column(name = "display_pattern", length = 256)
    public String getDisplayPattern() {
        return displayPattern;
    }

    public void setDisplayPattern(String displayPattern) {
        this.displayPattern = displayPattern;
    }

    public CategorySpec displayPattern(String displayPattern) {
        setDisplayPattern(displayPattern);
        return this;
    }
    // -- [isSpecInch] ------------------------

    @Size(max = 256)
    @Column(name = "is_spec_inch", length = 256)
    public String getIsSpecInch() {
        return isSpecInch;
    }

    public void setIsSpecInch(String isSpecInch) {
        this.isSpecInch = isSpecInch;
    }

    public CategorySpec isSpecInch(String isSpecInch) {
        setIsSpecInch(isSpecInch);
        return this;
    }
    // -- [similarFlag] ------------------------

    @Size(max = 256)
    @Column(name = "similar_flag", length = 256)
    public String getSimilarFlag() {
        return similarFlag;
    }

    public void setSimilarFlag(String similarFlag) {
        this.similarFlag = similarFlag;
    }

    public CategorySpec similarFlag(String similarFlag) {
        setSimilarFlag(similarFlag);
        return this;
    }
    // -- [groupTitle] ------------------------

    @Size(max = 256)
    @Column(name = "group_title", length = 256)
    public String getGroupTitle() {
        return groupTitle;
    }

    public void setGroupTitle(String groupTitle) {
        this.groupTitle = groupTitle;
    }

    public CategorySpec groupTitle(String groupTitle) {
        setGroupTitle(groupTitle);
        return this;
    }
    // -- [groupNoticeString] ------------------------

    @Size(max = 256)
    @Column(name = "group_notice_string", length = 256)
    public String getGroupNoticeString() {
        return groupNoticeString;
    }

    public void setGroupNoticeString(String groupNoticeString) {
        this.groupNoticeString = groupNoticeString;
    }

    public CategorySpec groupNoticeString(String groupNoticeString) {
        setGroupNoticeString(groupNoticeString);
        return this;
    }
    // -- [groupIndex] ------------------------

    @Size(max = 256)
    @Column(name = "group_index", length = 256)
    public String getGroupIndex() {
        return groupIndex;
    }

    public void setGroupIndex(String groupIndex) {
        this.groupIndex = groupIndex;
    }

    public CategorySpec groupIndex(String groupIndex) {
        setGroupIndex(groupIndex);
        return this;
    }
    // -- [isParent] ------------------------

    @Size(max = 256)
    @Column(name = "is_parent", length = 256)
    public String getIsParent() {
        return isParent;
    }

    public void setIsParent(String isParent) {
        this.isParent = isParent;
    }

    public CategorySpec isParent(String isParent) {
        setIsParent(isParent);
        return this;
    }

    /**
     * Apply the default values.
     */
    public CategorySpec withDefaults() {
        return this;
    }

    /**
     * Equals implementation using a business key.
     */
    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof CategorySpec && hashCode() == other.hashCode());
    }


    /**
     * Construct a readable string representation for this CategorySpec instance.
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this) //
                .add("id", getId()) //
                .add("categoryCode", getCategoryCode()) //
                .add("key", getKey()) //
                .add("title", getTitle()) //
                .add("unit", getUnit()) //
                .add("illustrationType", getIllustrationType()) //
                .add("categorySpecNo", getCategorySpecNo()) //
                .add("propertyCode", getPropertyCode()) //
                .add("aryChoiceName", getAryChoiceName()) //
                .add("aryChoiceCode", getAryChoiceCode()) //
                .add("valueType", getValueType()) //
                .add("extraSpec", getExtraSpec()) //
                .add("noticeString", getNoticeString()) //
                .add("hasParamSpec", getHasParamSpec()) //
                .add("useFlag", getUseFlag()) //
                .add("groupingStep", getGroupingStep()) //
                .add("displayPattern", getDisplayPattern()) //
                .add("isSpecInch", getIsSpecInch()) //
                .add("similarFlag", getSimilarFlag()) //
                .add("groupTitle", getGroupTitle()) //
                .add("groupNoticeString", getGroupNoticeString()) //
                .add("groupIndex", getGroupIndex()) //
                .add("isParent", getIsParent()) //
                .toString();
    }
}