/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-angular:src/main/java/domain/EntityMeta_.java.e.vm
 */
package com.sadetec.model;

import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@StaticMetamodel(CategorySpec.class)
public abstract class CategorySpec_ {

    // Raw attributes
    public static volatile SingularAttribute<CategorySpec, Integer> id;
    public static volatile SingularAttribute<CategorySpec, String> categoryCode;
    public static volatile SingularAttribute<CategorySpec, String> key;
    public static volatile SingularAttribute<CategorySpec, String> title;
    public static volatile SingularAttribute<CategorySpec, String> unit;
    public static volatile SingularAttribute<CategorySpec, String> illustrationType;
    public static volatile SingularAttribute<CategorySpec, String> categorySpecNo;
    public static volatile SingularAttribute<CategorySpec, String> propertyCode;
    public static volatile SingularAttribute<CategorySpec, String> aryChoiceName;
    public static volatile SingularAttribute<CategorySpec, String> aryChoiceCode;
    public static volatile SingularAttribute<CategorySpec, String> valueType;
    public static volatile SingularAttribute<CategorySpec, String> extraSpec;
    public static volatile SingularAttribute<CategorySpec, String> noticeString;
    public static volatile SingularAttribute<CategorySpec, String> hasParamSpec;
    public static volatile SingularAttribute<CategorySpec, String> useFlag;
    public static volatile SingularAttribute<CategorySpec, String> groupingStep;
    public static volatile SingularAttribute<CategorySpec, String> displayPattern;
    public static volatile SingularAttribute<CategorySpec, String> isSpecInch;
    public static volatile SingularAttribute<CategorySpec, String> similarFlag;
    public static volatile SingularAttribute<CategorySpec, String> groupTitle;
    public static volatile SingularAttribute<CategorySpec, String> groupNoticeString;
    public static volatile SingularAttribute<CategorySpec, String> groupIndex;
    public static volatile SingularAttribute<CategorySpec, String> isParent;
}