/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-angular:src/main/java/domain/EntityMeta_.java.e.vm
 */
package com.sadetec.model;

import java.time.LocalDateTime;

import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@StaticMetamodel(Category.class)
public abstract class Category_ {

    // Raw attributes
    public static volatile SingularAttribute<Category, String> id;
    public static volatile SingularAttribute<Category, String> categoryName;
    public static volatile SingularAttribute<Category, String> categoryUrl;
    public static volatile SingularAttribute<Category, Integer> categoryLevel;
    public static volatile SingularAttribute<Category, String> parentCode;
    public static volatile SingularAttribute<Category, Boolean> hasChildCategory;
    public static volatile SingularAttribute<Category, String> procBy;
    public static volatile SingularAttribute<Category, Boolean> procFlag;
    public static volatile SingularAttribute<Category, LocalDateTime> createDate;
    public static volatile SingularAttribute<Category, LocalDateTime> updateDate;
}