/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-angular:src/main/java/domain/EntityMeta_.java.e.vm
 */
package com.sadetec.model;

import java.time.LocalDateTime;

import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@StaticMetamodel(FormInstance.class)
public abstract class FormInstance_ {

    // Raw attributes
    public static volatile SingularAttribute<FormInstance, Integer> id;
    public static volatile SingularAttribute<FormInstance, String> title;
    public static volatile SingularAttribute<FormInstance, String> seqNumber;
    public static volatile SingularAttribute<FormInstance, String> drafterId;
    public static volatile SingularAttribute<FormInstance, String> drafter;
    public static volatile SingularAttribute<FormInstance, String> draftOrg;
    
    public static volatile SingularAttribute<FormInstance, String> salesId;
    public static volatile SingularAttribute<FormInstance, String> sales;
    public static volatile SingularAttribute<FormInstance, String> salesOrg;
    
    public static volatile SingularAttribute<FormInstance, String> comment;
    public static volatile SingularAttribute<FormInstance, String> description;
    public static volatile SingularAttribute<FormInstance, LocalDateTime> createDate;
    public static volatile SingularAttribute<FormInstance, LocalDateTime> lastModified;
    public static volatile SingularAttribute<FormInstance, String> processInstanceId;
    public static volatile SingularAttribute<FormInstance, String> processDefinitionId;
    public static volatile SingularAttribute<FormInstance, String> document;
    public static volatile SingularAttribute<FormInstance, Integer> priority;
}