/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-angular:src/main/java/domain/EntityMeta_.java.e.vm
 */
package com.sadetec.model;

import java.util.Date;

import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@StaticMetamodel(MailMessage.class)
public abstract class MailMessage_ {

    // Raw attributes
    public static volatile SingularAttribute<MailMessage, Integer> id;
    public static volatile SingularAttribute<MailMessage, Date> createDate;
    public static volatile SingularAttribute<MailMessage, Date> writeDate;
    public static volatile SingularAttribute<MailMessage, String> writeUid;
    public static volatile SingularAttribute<MailMessage, String> subject;
    public static volatile SingularAttribute<MailMessage, String> createUid;
    public static volatile SingularAttribute<MailMessage, Integer> parentId;
    public static volatile SingularAttribute<MailMessage, Integer> subtypeId;
    public static volatile SingularAttribute<MailMessage, Integer> resId;
    public static volatile SingularAttribute<MailMessage, String> body;
    public static volatile SingularAttribute<MailMessage, String> recordName;
    public static volatile SingularAttribute<MailMessage, Boolean> noAutoThread;
    public static volatile SingularAttribute<MailMessage, Date> date;
    public static volatile SingularAttribute<MailMessage, String> replyTo;
    public static volatile SingularAttribute<MailMessage, String> authorId;
    public static volatile SingularAttribute<MailMessage, String> model;
    public static volatile SingularAttribute<MailMessage, String> messageType;
    public static volatile SingularAttribute<MailMessage, String> emailFrom;
}