/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-angular:src/main/java/domain/Entity.java.e.vm
 */
package com.sadetec.model;

import static javax.persistence.GenerationType.IDENTITY;

import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.Date;
import java.util.logging.Logger;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.validation.constraints.Digits;
import javax.validation.constraints.Size;

import org.springframework.format.annotation.DateTimeFormat;

import com.google.common.base.MoreObjects;

@Entity
@Table(name = "mail_message")
public class MailMessage implements Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = Logger.getLogger(MailMessage.class.getName());

    // Raw attributes
    private Integer id;
    
	@Temporal(TemporalType.TIMESTAMP)
	@DateTimeFormat(style = "S-")
    private Date createDate;
    
	@Temporal(TemporalType.TIMESTAMP)
	@DateTimeFormat(style = "S-")
	private Date writeDate;
	
    private String writeUid;
    private String subject;
    private String createUid;
    private Integer parentId;
    private Integer subtypeId;
    private Integer resId;
    private String body;
    private String recordName;
    private Boolean noAutoThread;
    
	@Temporal(TemporalType.TIMESTAMP)
	@DateTimeFormat(style = "S-")
    private Date date;
	
    private String replyTo;
    private String authorId;
    private String model;
    private String messageType;
    private String emailFrom;

    public String entityClassName() {
        return MailMessage.class.getSimpleName();
    }

    // -- [id] ------------------------

    @Column(name = "id", precision = 10)
    @GeneratedValue(strategy = IDENTITY)
    @Id
    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public MailMessage id(Integer id) {
        setId(id);
        return this;
    }

    @Transient
    public boolean isIdSet() {
        return id != null;
    }
    // -- [createDate] ------------------------

    @Column(name = "create_date", length = 19)
    public Date getCreateDate() {
        return createDate;
    }

    public void setCreateDate(Date createDate) {
        this.createDate = createDate;
    }

    public MailMessage createDate(Date createDate) {
        setCreateDate(createDate);
        return this;
    }
    // -- [writeDate] ------------------------

    @Column(name = "write_date", length = 19)
    public Date getWriteDate() {
        return writeDate;
    }

    public void setWriteDate(Date writeDate) {
        this.writeDate = writeDate;
    }

    public MailMessage writeDate(Date writeDate) {
        setWriteDate(writeDate);
        return this;
    }
    // -- [writeUid] ------------------------

    @Size(max = 64)
    @Column(name = "write_uid", length = 64)
    public String getWriteUid() {
        return writeUid;
    }

    public void setWriteUid(String writeUid) {
        this.writeUid = writeUid;
    }

    public MailMessage writeUid(String writeUid) {
        setWriteUid(writeUid);
        return this;
    }
    // -- [subject] ------------------------

    @Size(max = 256)
    @Column(name = "subject", length = 256)
    public String getSubject() {
        return subject;
    }

    public void setSubject(String subject) {
        this.subject = subject;
    }

    public MailMessage subject(String subject) {
        setSubject(subject);
        return this;
    }
    // -- [createUid] ------------------------

    @Size(max = 64)
    @Column(name = "create_uid", length = 64)
    public String getCreateUid() {
        return createUid;
    }

    public void setCreateUid(String createUid) {
        this.createUid = createUid;
    }

    public MailMessage createUid(String createUid) {
        setCreateUid(createUid);
        return this;
    }
    // -- [parentId] ------------------------

    @Digits(integer = 10, fraction = 0)
    @Column(name = "parent_id", precision = 10)
    public Integer getParentId() {
        return parentId;
    }

    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    public MailMessage parentId(Integer parentId) {
        setParentId(parentId);
        return this;
    }
    // -- [subtypeId] ------------------------

    @Digits(integer = 10, fraction = 0)
    @Column(name = "subtype_id", precision = 10)
    public Integer getSubtypeId() {
        return subtypeId;
    }

    public void setSubtypeId(Integer subtypeId) {
        this.subtypeId = subtypeId;
    }

    public MailMessage subtypeId(Integer subtypeId) {
        setSubtypeId(subtypeId);
        return this;
    }
    // -- [resId] ------------------------

    @Digits(integer = 10, fraction = 0)
    @Column(name = "res_id", precision = 10)
    public Integer getResId() {
        return resId;
    }

    public void setResId(Integer resId) {
        this.resId = resId;
    }

    public MailMessage resId(Integer resId) {
        setResId(resId);
        return this;
    }
    // -- [body] ------------------------

    @Size(max = 65535)
    @Column(name = "`body`", length = 65535)
    public String getBody() {
        return body;
    }

    public void setBody(String body) {
        this.body = body;
    }

    public MailMessage body(String body) {
        setBody(body);
        return this;
    }
    // -- [recordName] ------------------------

    @Size(max = 64)
    @Column(name = "record_name", length = 64)
    public String getRecordName() {
        return recordName;
    }

    public void setRecordName(String recordName) {
        this.recordName = recordName;
    }

    public MailMessage recordName(String recordName) {
        setRecordName(recordName);
        return this;
    }
    // -- [noAutoThread] ------------------------

    @Column(name = "no_auto_thread", length = 0)
    public Boolean getNoAutoThread() {
        return noAutoThread;
    }

    public void setNoAutoThread(Boolean noAutoThread) {
        this.noAutoThread = noAutoThread;
    }

    public MailMessage noAutoThread(Boolean noAutoThread) {
        setNoAutoThread(noAutoThread);
        return this;
    }
    // -- [date] ------------------------

    @Column(name = "`date`", length = 19)
    public Date getDate() {
        return date;
    }

    public void setDate(Date date) {
        this.date = date;
    }

    public MailMessage date(Date date) {
        setDate(date);
        return this;
    }
    // -- [replyTo] ------------------------

    @Size(max = 64)
    @Column(name = "reply_to", length = 64)
    public String getReplyTo() {
        return replyTo;
    }

    public void setReplyTo(String replyTo) {
        this.replyTo = replyTo;
    }

    public MailMessage replyTo(String replyTo) {
        setReplyTo(replyTo);
        return this;
    }
    // -- [authorId] ------------------------

    @Size(max = 64)
    @Column(name = "author_id", length = 64)
    public String getAuthorId() {
        return authorId;
    }

    public void setAuthorId(String authorId) {
        this.authorId = authorId;
    }

    public MailMessage authorId(String authorId) {
        setAuthorId(authorId);
        return this;
    }
    // -- [model] ------------------------

    @Size(max = 64)
    @Column(name = "model", length = 64)
    public String getModel() {
        return model;
    }

    public void setModel(String model) {
        this.model = model;
    }

    public MailMessage model(String model) {
        setModel(model);
        return this;
    }
    // -- [messageType] ------------------------

    @Size(max = 64)
    @Column(name = "message_type", length = 64)
    public String getMessageType() {
        return messageType;
    }

    public void setMessageType(String messageType) {
        this.messageType = messageType;
    }

    public MailMessage messageType(String messageType) {
        setMessageType(messageType);
        return this;
    }
    // -- [emailFrom] ------------------------

    @Size(max = 64)
    @Column(name = "email_from", length = 64)
    public String getEmailFrom() {
        return emailFrom;
    }

    public void setEmailFrom(String emailFrom) {
        this.emailFrom = emailFrom;
    }

    public MailMessage emailFrom(String emailFrom) {
        setEmailFrom(emailFrom);
        return this;
    }

    /**
     * Apply the default values.
     */
    public MailMessage withDefaults() {
        return this;
    }

    /**
     * Equals implementation using a business key.
     */
    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof MailMessage && hashCode() == other.hashCode());
    }


    /**
     * Construct a readable string representation for this MailMessage instance.
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this) //
                .add("id", getId()) //
                .add("createDate", getCreateDate()) //
                .add("writeDate", getWriteDate()) //
                .add("writeUid", getWriteUid()) //
                .add("subject", getSubject()) //
                .add("createUid", getCreateUid()) //
                .add("parentId", getParentId()) //
                .add("subtypeId", getSubtypeId()) //
                .add("resId", getResId()) //
                .add("body", getBody()) //
                .add("recordName", getRecordName()) //
                .add("noAutoThread", getNoAutoThread()) //
                .add("date", getDate()) //
                .add("replyTo", getReplyTo()) //
                .add("authorId", getAuthorId()) //
                .add("model", getModel()) //
                .add("messageType", getMessageType()) //
                .add("emailFrom", getEmailFrom()) //
                .toString();
    }
}