/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-angular:src/main/java/domain/EntityMeta_.java.e.vm
 */
package com.sadetec.model;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@StaticMetamodel(ManualProductMap.class)
public abstract class ManualProductMap_ {

    // Raw attributes
    public static volatile SingularAttribute<ManualProductMap, String> id;
    public static volatile SingularAttribute<ManualProductMap, String> atProductName;
    public static volatile SingularAttribute<ManualProductMap, String> atProductDesc;
    public static volatile SingularAttribute<ManualProductMap, String> miProductName;
    public static volatile SingularAttribute<ManualProductMap, String> miProductCode;
    public static volatile SingularAttribute<ManualProductMap, String> miProductDesc;
    public static volatile SingularAttribute<ManualProductMap, BigDecimal> miProductQuote;
    public static volatile SingularAttribute<ManualProductMap, BigDecimal> atProductQuote;
    public static volatile SingularAttribute<ManualProductMap, BigDecimal> factoryQuote;
    public static volatile SingularAttribute<ManualProductMap, BigDecimal> uniQuote;
    public static volatile SingularAttribute<ManualProductMap, BigDecimal> supaQuote;
    public static volatile SingularAttribute<ManualProductMap, BigDecimal> supbQuote;
    public static volatile SingularAttribute<ManualProductMap, BigDecimal> supcQuote;
    public static volatile SingularAttribute<ManualProductMap, LocalDateTime> createDate;
    public static volatile SingularAttribute<ManualProductMap, LocalDateTime> updateDate;
}