/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-angular:src/main/java/domain/Entity.java.e.vm
 */
package com.sadetec.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.logging.Logger;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.Digits;
import javax.validation.constraints.Size;

import org.hibernate.validator.constraints.NotEmpty;

import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;

@Entity
@Table(name = "manual_product_map")
public class ManualProductMap implements Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = Logger.getLogger(ManualProductMap.class.getName());

    // Raw attributes
    private String id;
    private String atProductName;
    private String atProductDesc;
    private String miProductName;
    private String miProductCode;
    private String miProductDesc;
    private BigDecimal miProductQuote;
    private BigDecimal atProductQuote;
    private BigDecimal factoryQuote;
    private BigDecimal uniQuote;
    private BigDecimal supaQuote;
    private BigDecimal supbQuote;
    private BigDecimal supcQuote;
    private LocalDateTime createDate;
    private LocalDateTime updateDate;

    public String entityClassName() {
        return ManualProductMap.class.getSimpleName();
    }

    // -- [id] ------------------------

    @NotEmpty
    @Size(max = 128)
    @Column(name = "at_product_code", length = 128)
    @Id
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public ManualProductMap id(String id) {
        setId(id);
        return this;
    }

    @Transient
    public boolean isIdSet() {
        return id != null && !id.isEmpty();
    }
    // -- [atProductName] ------------------------

    @Size(max = 256)
    @Column(name = "at_product_name", length = 256)
    public String getAtProductName() {
        return atProductName;
    }

    public void setAtProductName(String atProductName) {
        this.atProductName = atProductName;
    }

    public ManualProductMap atProductName(String atProductName) {
        setAtProductName(atProductName);
        return this;
    }
    // -- [atProductDesc] ------------------------

    @Size(max = 512)
    @Column(name = "at_product_desc", length = 512)
    public String getAtProductDesc() {
        return atProductDesc;
    }

    public void setAtProductDesc(String atProductDesc) {
        this.atProductDesc = atProductDesc;
    }

    public ManualProductMap atProductDesc(String atProductDesc) {
        setAtProductDesc(atProductDesc);
        return this;
    }
    // -- [miProductName] ------------------------

    @Size(max = 256)
    @Column(name = "mi_product_name", length = 256)
    public String getMiProductName() {
        return miProductName;
    }

    public void setMiProductName(String miProductName) {
        this.miProductName = miProductName;
    }

    public ManualProductMap miProductName(String miProductName) {
        setMiProductName(miProductName);
        return this;
    }
    // -- [miProductCode] ------------------------

    @Size(max = 256)
    @Column(name = "mi_product_code", length = 256)
    public String getMiProductCode() {
        return miProductCode;
    }

    public void setMiProductCode(String miProductCode) {
        this.miProductCode = miProductCode;
    }

    public ManualProductMap miProductCode(String miProductCode) {
        setMiProductCode(miProductCode);
        return this;
    }
    // -- [miProductDesc] ------------------------

    @Size(max = 512)
    @Column(name = "mi_product_desc", length = 512)
    public String getMiProductDesc() {
        return miProductDesc;
    }

    public void setMiProductDesc(String miProductDesc) {
        this.miProductDesc = miProductDesc;
    }

    public ManualProductMap miProductDesc(String miProductDesc) {
        setMiProductDesc(miProductDesc);
        return this;
    }
    // -- [miProductQuote] ------------------------

    @Digits(integer = 11, fraction = 4)
    @Column(name = "mi_product_quote", precision = 15, scale = 4)
    public BigDecimal getMiProductQuote() {
        return miProductQuote;
    }

    public void setMiProductQuote(BigDecimal miProductQuote) {
        this.miProductQuote = miProductQuote;
    }

    public ManualProductMap miProductQuote(BigDecimal miProductQuote) {
        setMiProductQuote(miProductQuote);
        return this;
    }
    // -- [atProductQuote] ------------------------

    @Digits(integer = 11, fraction = 4)
    @Column(name = "at_product_quote", precision = 15, scale = 4)
    public BigDecimal getAtProductQuote() {
        return atProductQuote;
    }

    public void setAtProductQuote(BigDecimal atProductQuote) {
        this.atProductQuote = atProductQuote;
    }

    public ManualProductMap atProductQuote(BigDecimal atProductQuote) {
        setAtProductQuote(atProductQuote);
        return this;
    }
    // -- [factoryQuote] ------------------------

    @Digits(integer = 11, fraction = 4)
    @Column(name = "factory_quote", precision = 15, scale = 4)
    public BigDecimal getFactoryQuote() {
        return factoryQuote;
    }

    public void setFactoryQuote(BigDecimal factoryQuote) {
        this.factoryQuote = factoryQuote;
    }

    public ManualProductMap factoryQuote(BigDecimal factoryQuote) {
        setFactoryQuote(factoryQuote);
        return this;
    }
    // -- [uniQuote] ------------------------

    @Digits(integer = 11, fraction = 4)
    @Column(name = "uni_quote", precision = 15, scale = 4)
    public BigDecimal getUniQuote() {
        return uniQuote;
    }

    public void setUniQuote(BigDecimal uniQuote) {
        this.uniQuote = uniQuote;
    }

    public ManualProductMap uniQuote(BigDecimal uniQuote) {
        setUniQuote(uniQuote);
        return this;
    }
    // -- [supaQuote] ------------------------

    /**
     * ??,???A??
     */
    @Digits(integer = 11, fraction = 4)
    @Column(name = "supa_quote", precision = 15, scale = 4)
    public BigDecimal getSupaQuote() {
        return supaQuote;
    }

    public void setSupaQuote(BigDecimal supaQuote) {
        this.supaQuote = supaQuote;
    }

    public ManualProductMap supaQuote(BigDecimal supaQuote) {
        setSupaQuote(supaQuote);
        return this;
    }
    // -- [supbQuote] ------------------------

    /**
     * ??,???B??
     */
    @Digits(integer = 11, fraction = 4)
    @Column(name = "supb_quote", precision = 15, scale = 4)
    public BigDecimal getSupbQuote() {
        return supbQuote;
    }

    public void setSupbQuote(BigDecimal supbQuote) {
        this.supbQuote = supbQuote;
    }

    public ManualProductMap supbQuote(BigDecimal supbQuote) {
        setSupbQuote(supbQuote);
        return this;
    }
    // -- [supcQuote] ------------------------

    /**
     * ??,???C??
     */
    @Digits(integer = 11, fraction = 4)
    @Column(name = "supc_quote", precision = 15, scale = 4)
    public BigDecimal getSupcQuote() {
        return supcQuote;
    }

    public void setSupcQuote(BigDecimal supcQuote) {
        this.supcQuote = supcQuote;
    }

    public ManualProductMap supcQuote(BigDecimal supcQuote) {
        setSupcQuote(supcQuote);
        return this;
    }
    // -- [createDate] ------------------------

    /**
     * 创建时间
     */
    @Column(name = "create_date", length = 19)
    public LocalDateTime getCreateDate() {
        return createDate;
    }

    public void setCreateDate(LocalDateTime createDate) {
        this.createDate = createDate;
    }

    public ManualProductMap createDate(LocalDateTime createDate) {
        setCreateDate(createDate);
        return this;
    }
    // -- [updateDate] ------------------------

    /**
     * 更新时间
     */
    @Column(name = "update_date", length = 19)
    public LocalDateTime getUpdateDate() {
        return updateDate;
    }

    public void setUpdateDate(LocalDateTime updateDate) {
        this.updateDate = updateDate;
    }

    public ManualProductMap updateDate(LocalDateTime updateDate) {
        setUpdateDate(updateDate);
        return this;
    }

    /**
     * Apply the default values.
     */
    public ManualProductMap withDefaults() {
        setMiProductQuote(new BigDecimal("0.0000"));
        setAtProductQuote(new BigDecimal("0.0000"));
        setFactoryQuote(new BigDecimal("0.0000"));
        setUniQuote(new BigDecimal("0.0000"));
        setSupaQuote(new BigDecimal("0.0000"));
        setSupbQuote(new BigDecimal("0.0000"));
        setSupcQuote(new BigDecimal("0.0000"));
        return this;
    }

    /**
     * Equals implementation using a business key.
     */
    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof ManualProductMap && hashCode() == other.hashCode());
    }


    /**
     * Construct a readable string representation for this ManualProductMap instance.
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this) //
                .add("id", getId()) //
                .add("atProductName", getAtProductName()) //
                .add("atProductDesc", getAtProductDesc()) //
                .add("miProductName", getMiProductName()) //
                .add("miProductCode", getMiProductCode()) //
                .add("miProductDesc", getMiProductDesc()) //
                .add("miProductQuote", getMiProductQuote()) //
                .add("atProductQuote", getAtProductQuote()) //
                .add("factoryQuote", getFactoryQuote()) //
                .add("uniQuote", getUniQuote()) //
                .add("supaQuote", getSupaQuote()) //
                .add("supbQuote", getSupbQuote()) //
                .add("supcQuote", getSupcQuote()) //
                .add("createDate", getCreateDate()) //
                .add("updateDate", getUpdateDate()) //
                .toString();
    }
}