/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-angular:src/main/java/domain/Entity.java.e.vm
 */
package com.sadetec.model;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.logging.Logger;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.Digits;
import javax.validation.constraints.Size;

import org.hibernate.validator.constraints.NotEmpty;
import org.hibernate.validator.constraints.URL;

import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;

@Entity
@Table(name = "product")
public class Product implements Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = Logger.getLogger(Product.class.getName());

    // Raw attributes
    private String id;
    private String productName;
    private String productUrl;
    private String productSpec;
    private String typeCode;
    private String typeName;
    private String brdName;
    private String brdCode;
    private String seriesCode;
    private BigDecimal unitPrice;
    private String procBy;
    private Boolean procFlag;
    private LocalDateTime createDate;
    private LocalDateTime updateDate;

    public String entityClassName() {
        return Product.class.getSimpleName();
    }

    // -- [id] ------------------------

    @NotEmpty
    @Size(max = 128)
    @Column(name = "product_code", length = 128)
    @Id
    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public Product id(String id) {
        setId(id);
        return this;
    }

    @Transient
    public boolean isIdSet() {
        return id != null && !id.isEmpty();
    }
    // -- [productName] ------------------------

    @NotEmpty
    @Size(max = 256)
    @Column(name = "product_name", nullable = false, length = 256)
    public String getProductName() {
        return productName;
    }

    public void setProductName(String productName) {
        this.productName = productName;
    }

    public Product productName(String productName) {
        setProductName(productName);
        return this;
    }
    // -- [productUrl] ------------------------

    @NotEmpty
    @Size(max = 512)
    @URL
    @Column(name = "product_url", nullable = false, length = 512)
    public String getProductUrl() {
        return productUrl;
    }

    public void setProductUrl(String productUrl) {
        this.productUrl = productUrl;
    }

    public Product productUrl(String productUrl) {
        setProductUrl(productUrl);
        return this;
    }
    // -- [productSpec] ------------------------

    /**
     * 产品规格参数表达式ROGAK{}-{}-{}
     */
    @Size(max = 256)
    @Column(name = "product_spec", length = 256)
    public String getProductSpec() {
        return productSpec;
    }

    public void setProductSpec(String productSpec) {
        this.productSpec = productSpec;
    }

    public Product productSpec(String productSpec) {
        setProductSpec(productSpec);
        return this;
    }
    // -- [typeCode] ------------------------

    /**
     * 产品类型00000042758
     */
    @Size(max = 256)
    @Column(name = "type_code", length = 256)
    public String getTypeCode() {
        return typeCode;
    }

    public void setTypeCode(String typeCode) {
        this.typeCode = typeCode;
    }

    public Product typeCode(String typeCode) {
        setTypeCode(typeCode);
        return this;
    }
    // -- [typeName] ------------------------

    /**
     * 类型名称ROGAK
     */
    @Size(max = 512)
    @Column(name = "type_name", length = 512)
    public String getTypeName() {
        return typeName;
    }

    public void setTypeName(String typeName) {
        this.typeName = typeName;
    }

    public Product typeName(String typeName) {
        setTypeName(typeName);
        return this;
    }
    // -- [brdName] ------------------------

    @Size(max = 256)
    @Column(name = "brd_name", length = 256)
    public String getBrdName() {
        return brdName;
    }

    public void setBrdName(String brdName) {
        this.brdName = brdName;
    }

    public Product brdName(String brdName) {
        setBrdName(brdName);
        return this;
    }
    // -- [brdCode] ------------------------

    @Size(max = 256)
    @Column(name = "brd_code", length = 256)
    public String getBrdCode() {
        return brdCode;
    }

    public void setBrdCode(String brdCode) {
        this.brdCode = brdCode;
    }

    public Product brdCode(String brdCode) {
        setBrdCode(brdCode);
        return this;
    }
    // -- [seriesCode] ------------------------

    @Size(max = 256)
    @Column(name = "series_code", length = 256)
    public String getSeriesCode() {
        return seriesCode;
    }

    public void setSeriesCode(String seriesCode) {
        this.seriesCode = seriesCode;
    }

    public Product seriesCode(String seriesCode) {
        setSeriesCode(seriesCode);
        return this;
    }
    // -- [unitPrice] ------------------------

    @Digits(integer = 11, fraction = 4)
    @Column(name = "unit_price", precision = 15, scale = 4)
    public BigDecimal getUnitPrice() {
        return unitPrice;
    }

    public void setUnitPrice(BigDecimal unitPrice) {
        this.unitPrice = unitPrice;
    }

    public Product unitPrice(BigDecimal unitPrice) {
        setUnitPrice(unitPrice);
        return this;
    }
    // -- [procBy] ------------------------

    /**
     * 多处理线程时每个线程标识
     */
    @Size(max = 255)
    @Column(name = "proc_by")
    public String getProcBy() {
        return procBy;
    }

    public void setProcBy(String procBy) {
        this.procBy = procBy;
    }

    public Product procBy(String procBy) {
        setProcBy(procBy);
        return this;
    }
    // -- [procFlag] ------------------------

    /**
     * 处理标记 1：已完成 0：未完成
     */
    @Column(name = "proc_flag", length = 0)
    public Boolean getProcFlag() {
        return procFlag;
    }

    public void setProcFlag(Boolean procFlag) {
        this.procFlag = procFlag;
    }

    public Product procFlag(Boolean procFlag) {
        setProcFlag(procFlag);
        return this;
    }
    // -- [createDate] ------------------------

    /**
     * 创建时间
     */
    @Column(name = "create_date", length = 19)
    public LocalDateTime getCreateDate() {
        return createDate;
    }

    public void setCreateDate(LocalDateTime createDate) {
        this.createDate = createDate;
    }

    public Product createDate(LocalDateTime createDate) {
        setCreateDate(createDate);
        return this;
    }
    // -- [updateDate] ------------------------

    /**
     * 更新时间
     */
    @Column(name = "update_date", length = 19)
    public LocalDateTime getUpdateDate() {
        return updateDate;
    }

    public void setUpdateDate(LocalDateTime updateDate) {
        this.updateDate = updateDate;
    }

    public Product updateDate(LocalDateTime updateDate) {
        setUpdateDate(updateDate);
        return this;
    }

    /**
     * Apply the default values.
     */
    public Product withDefaults() {
        setUnitPrice(new BigDecimal("0.0000"));
        return this;
    }

    /**
     * Equals implementation using a business key.
     */
    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof Product && hashCode() == other.hashCode());
    }


    /**
     * Construct a readable string representation for this Product instance.
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this) //
                .add("id", getId()) //
                .add("productName", getProductName()) //
                .add("productUrl", getProductUrl()) //
                .add("productSpec", getProductSpec()) //
                .add("typeCode", getTypeCode()) //
                .add("typeName", getTypeName()) //
                .add("brdName", getBrdName()) //
                .add("brdCode", getBrdCode()) //
                .add("seriesCode", getSeriesCode()) //
                .add("unitPrice", getUnitPrice()) //
                .add("procBy", getProcBy()) //
                .add("procFlag", getProcFlag()) //
                .add("createDate", getCreateDate()) //
                .add("updateDate", getUpdateDate()) //
                .toString();
    }
}