/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-angular:src/main/java/domain/Entity.java.e.vm
 */
package com.sadetec.model;

import static javax.persistence.GenerationType.IDENTITY;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.logging.Logger;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.Digits;
import javax.validation.constraints.Size;

import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;

@Entity
@Table(name = "product_supplierinfo")
public class ProductSupplierinfo implements Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = Logger.getLogger(ProductSupplierinfo.class.getName());

    // Raw attributes
    private Integer id;
    private String createUid;
    private LocalDateTime createDate;
    private Integer delay;
    private Integer sequence;
    private LocalDateTime dateStart;
    private LocalDateTime dateEnd;
    private Integer companyId;
    private String companyName;
    private String productName;
    private String productCode;
    private BigDecimal minQty;
    private BigDecimal price;
    private String productId;

    public String entityClassName() {
        return ProductSupplierinfo.class.getSimpleName();
    }

    // -- [id] ------------------------

    @Column(name = "id", precision = 10)
    @GeneratedValue(strategy = IDENTITY)
    @Id
    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public ProductSupplierinfo id(Integer id) {
        setId(id);
        return this;
    }

    @Transient
    public boolean isIdSet() {
        return id != null;
    }
    // -- [createUid] ------------------------

    /**
     * 添加人
     */
    @Size(max = 64)
    @Column(name = "create_uid", length = 64)
    public String getCreateUid() {
        return createUid;
    }

    public void setCreateUid(String createUid) {
        this.createUid = createUid;
    }

    public ProductSupplierinfo createUid(String createUid) {
        setCreateUid(createUid);
        return this;
    }
    // -- [createDate] ------------------------

    /**
     * 添加日期
     */
    @Column(name = "create_date", length = 19)
    public LocalDateTime getCreateDate() {
        return createDate;
    }

    public void setCreateDate(LocalDateTime createDate) {
        this.createDate = createDate;
    }

    public ProductSupplierinfo createDate(LocalDateTime createDate) {
        setCreateDate(createDate);
        return this;
    }
    // -- [delay] ------------------------

    /**
     * 交货前置时间天
     */
    @Digits(integer = 10, fraction = 0)
    @Column(name = "`delay`", precision = 10)
    public Integer getDelay() {
        return delay;
    }

    public void setDelay(Integer delay) {
        this.delay = delay;
    }

    public ProductSupplierinfo delay(Integer delay) {
        setDelay(delay);
        return this;
    }
    // -- [sequence] ------------------------

    /**
     * 顺序
     */
    @Digits(integer = 10, fraction = 0)
    @Column(name = "`sequence`", precision = 10)
    public Integer getSequence() {
        return sequence;
    }

    public void setSequence(Integer sequence) {
        this.sequence = sequence;
    }

    public ProductSupplierinfo sequence(Integer sequence) {
        setSequence(sequence);
        return this;
    }
    // -- [dateStart] ------------------------

    /**
     * 价格开始日期
     */
    @Column(name = "date_start", length = 19)
    public LocalDateTime getDateStart() {
        return dateStart;
    }

    public void setDateStart(LocalDateTime dateStart) {
        this.dateStart = dateStart;
    }

    public ProductSupplierinfo dateStart(LocalDateTime dateStart) {
        setDateStart(dateStart);
        return this;
    }
    // -- [dateEnd] ------------------------

    /**
     * 价格结束日期
     */
    @Column(name = "date_end", length = 19)
    public LocalDateTime getDateEnd() {
        return dateEnd;
    }

    public void setDateEnd(LocalDateTime dateEnd) {
        this.dateEnd = dateEnd;
    }

    public ProductSupplierinfo dateEnd(LocalDateTime dateEnd) {
        setDateEnd(dateEnd);
        return this;
    }
    // -- [companyId] ------------------------

    /**
     * 公司ID
     */
    @Digits(integer = 10, fraction = 0)
    @Column(name = "company_id", precision = 10)
    public Integer getCompanyId() {
        return companyId;
    }

    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    public ProductSupplierinfo companyId(Integer companyId) {
        setCompanyId(companyId);
        return this;
    }
    // -- [companyName] ------------------------

    /**
     * 公司名称
     */
    @Size(max = 256)
    @Column(name = "company_name", length = 256)
    public String getCompanyName() {
        return companyName;
    }

    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    public ProductSupplierinfo companyName(String companyName) {
        setCompanyName(companyName);
        return this;
    }
    // -- [productName] ------------------------

    /**
     * 显示名称
     */
    @Size(max = 256)
    @Column(name = "product_name", length = 256)
    public String getProductName() {
        return productName;
    }

    public void setProductName(String productName) {
        this.productName = productName;
    }

    public ProductSupplierinfo productName(String productName) {
        setProductName(productName);
        return this;
    }
    // -- [productCode] ------------------------

    /**
     * 产品型号
     */
    @Size(max = 256)
    @Column(name = "product_code", length = 256)
    public String getProductCode() {
        return productCode;
    }

    public void setProductCode(String productCode) {
        this.productCode = productCode;
    }

    public ProductSupplierinfo productCode(String productCode) {
        setProductCode(productCode);
        return this;
    }
    // -- [minQty] ------------------------

    /**
     * 最小数量
     */
    @Digits(integer = 11, fraction = 4)
    @Column(name = "min_qty", precision = 15, scale = 4)
    public BigDecimal getMinQty() {
        return minQty;
    }

    public void setMinQty(BigDecimal minQty) {
        this.minQty = minQty;
    }

    public ProductSupplierinfo minQty(BigDecimal minQty) {
        setMinQty(minQty);
        return this;
    }
    // -- [price] ------------------------

    /**
     * 价格
     */
    @Digits(integer = 11, fraction = 4)
    @Column(name = "price", precision = 15, scale = 4)
    public BigDecimal getPrice() {
        return price;
    }

    public void setPrice(BigDecimal price) {
        this.price = price;
    }

    public ProductSupplierinfo price(BigDecimal price) {
        setPrice(price);
        return this;
    }
    // -- [productId] ------------------------

    /**
     * 产品标识
     */
    @Size(max = 256)
    @Column(name = "product_id", length = 256)
    public String getProductId() {
        return productId;
    }

    public void setProductId(String productId) {
        this.productId = productId;
    }

    public ProductSupplierinfo productId(String productId) {
        setProductId(productId);
        return this;
    }

    /**
     * Apply the default values.
     */
    public ProductSupplierinfo withDefaults() {
        setMinQty(new BigDecimal("0.0000"));
        setPrice(new BigDecimal("0.0000"));
        return this;
    }

    /**
     * Equals implementation using a business key.
     */
    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof ProductSupplierinfo && hashCode() == other.hashCode());
    }
  

    /**
     * Construct a readable string representation for this ProductSupplierinfo instance.
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this) //
                .add("id", getId()) //
                .add("createUid", getCreateUid()) //
                .add("createDate", getCreateDate()) //
                .add("delay", getDelay()) //
                .add("sequence", getSequence()) //
                .add("dateStart", getDateStart()) //
                .add("dateEnd", getDateEnd()) //
                .add("companyId", getCompanyId()) //
                .add("companyName", getCompanyName()) //
                .add("productName", getProductName()) //
                .add("productCode", getProductCode()) //
                .add("minQty", getMinQty()) //
                .add("price", getPrice()) //
                .add("productId", getProductId()) //
                .toString();
    }
}