/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-angular:src/main/java/domain/Entity.java.e.vm
 */
package com.sadetec.model;

import static javax.persistence.GenerationType.IDENTITY;

import java.io.Serializable;
import java.math.BigDecimal;
import java.util.logging.Logger;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.Digits;
import javax.validation.constraints.Size;

import org.hibernate.validator.constraints.NotEmpty;

import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;

@Entity
@Table(name = "quotation_history")
public class QuotationHistory implements Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = Logger.getLogger(QuotationHistory.class.getName());

    // Raw attributes
    private Integer id;
    private String atProductCode;
    private String atProductName;
    private String atProductDesc;
    private String miProductName;
    private String miProductCode;
    private String miProductDesc;
    private BigDecimal miProductQuote;
    private BigDecimal atProductQuote;
    private BigDecimal factoryQuote;
    private BigDecimal uniQuote;
    private BigDecimal supaQuote;
    private BigDecimal supbQuote;
    private BigDecimal supcQuote;
    private String loginName;
    private String productCode;
    private Integer orderQuantity;
    private String procBy;
    private Boolean procFlag;

    public String entityClassName() {
        return QuotationHistory.class.getSimpleName();
    }

    // -- [id] ------------------------

    @Column(name = "id", precision = 10)
    @GeneratedValue(strategy = IDENTITY)
    @Id
    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public QuotationHistory id(Integer id) {
        setId(id);
        return this;
    }

    @Transient
    public boolean isIdSet() {
        return id != null;
    }
    // -- [atProductCode] ------------------------

    @NotEmpty
    @Size(max = 256)
    @Column(name = "at_product_code", nullable = false, length = 256)
    public String getAtProductCode() {
        return atProductCode;
    }

    public void setAtProductCode(String atProductCode) {
        this.atProductCode = atProductCode;
    }

    public QuotationHistory atProductCode(String atProductCode) {
        setAtProductCode(atProductCode);
        return this;
    }
    // -- [atProductName] ------------------------

    @Size(max = 256)
    @Column(name = "at_product_name", length = 256)
    public String getAtProductName() {
        return atProductName;
    }

    public void setAtProductName(String atProductName) {
        this.atProductName = atProductName;
    }

    public QuotationHistory atProductName(String atProductName) {
        setAtProductName(atProductName);
        return this;
    }
    // -- [atProductDesc] ------------------------

    @Size(max = 512)
    @Column(name = "at_product_desc", length = 512)
    public String getAtProductDesc() {
        return atProductDesc;
    }

    public void setAtProductDesc(String atProductDesc) {
        this.atProductDesc = atProductDesc;
    }

    public QuotationHistory atProductDesc(String atProductDesc) {
        setAtProductDesc(atProductDesc);
        return this;
    }
    // -- [miProductName] ------------------------

    @Size(max = 256)
    @Column(name = "mi_product_name", length = 256)
    public String getMiProductName() {
        return miProductName;
    }

    public void setMiProductName(String miProductName) {
        this.miProductName = miProductName;
    }

    public QuotationHistory miProductName(String miProductName) {
        setMiProductName(miProductName);
        return this;
    }
    // -- [miProductCode] ------------------------

    @Size(max = 256)
    @Column(name = "mi_product_code", length = 256)
    public String getMiProductCode() {
        return miProductCode;
    }

    public void setMiProductCode(String miProductCode) {
        this.miProductCode = miProductCode;
    }

    public QuotationHistory miProductCode(String miProductCode) {
        setMiProductCode(miProductCode);
        return this;
    }
    // -- [miProductDesc] ------------------------

    @Size(max = 512)
    @Column(name = "mi_product_desc", length = 512)
    public String getMiProductDesc() {
        return miProductDesc;
    }

    public void setMiProductDesc(String miProductDesc) {
        this.miProductDesc = miProductDesc;
    }

    public QuotationHistory miProductDesc(String miProductDesc) {
        setMiProductDesc(miProductDesc);
        return this;
    }
    // -- [miProductQuote] ------------------------

    @Digits(integer = 11, fraction = 4)
    @Column(name = "mi_product_quote", precision = 15, scale = 4)
    public BigDecimal getMiProductQuote() {
        return miProductQuote;
    }

    public void setMiProductQuote(BigDecimal miProductQuote) {
        this.miProductQuote = miProductQuote;
    }

    public QuotationHistory miProductQuote(BigDecimal miProductQuote) {
        setMiProductQuote(miProductQuote);
        return this;
    }
    // -- [atProductQuote] ------------------------

    @Digits(integer = 11, fraction = 4)
    @Column(name = "at_product_quote", precision = 15, scale = 4)
    public BigDecimal getAtProductQuote() {
        return atProductQuote;
    }

    public void setAtProductQuote(BigDecimal atProductQuote) {
        this.atProductQuote = atProductQuote;
    }

    public QuotationHistory atProductQuote(BigDecimal atProductQuote) {
        setAtProductQuote(atProductQuote);
        return this;
    }
    // -- [factoryQuote] ------------------------

    @Digits(integer = 11, fraction = 4)
    @Column(name = "factory_quote", precision = 15, scale = 4)
    public BigDecimal getFactoryQuote() {
        return factoryQuote;
    }

    public void setFactoryQuote(BigDecimal factoryQuote) {
        this.factoryQuote = factoryQuote;
    }

    public QuotationHistory factoryQuote(BigDecimal factoryQuote) {
        setFactoryQuote(factoryQuote);
        return this;
    }
    // -- [uniQuote] ------------------------

    @Digits(integer = 11, fraction = 4)
    @Column(name = "uni_quote", precision = 15, scale = 4)
    public BigDecimal getUniQuote() {
        return uniQuote;
    }

    public void setUniQuote(BigDecimal uniQuote) {
        this.uniQuote = uniQuote;
    }

    public QuotationHistory uniQuote(BigDecimal uniQuote) {
        setUniQuote(uniQuote);
        return this;
    }
    // -- [supaQuote] ------------------------

    @Digits(integer = 11, fraction = 4)
    @Column(name = "supa_quote", precision = 15, scale = 4)
    public BigDecimal getSupaQuote() {
        return supaQuote;
    }

    public void setSupaQuote(BigDecimal supaQuote) {
        this.supaQuote = supaQuote;
    }

    public QuotationHistory supaQuote(BigDecimal supaQuote) {
        setSupaQuote(supaQuote);
        return this;
    }
    // -- [supbQuote] ------------------------

    @Digits(integer = 11, fraction = 4)
    @Column(name = "supb_quote", precision = 15, scale = 4)
    public BigDecimal getSupbQuote() {
        return supbQuote;
    }

    public void setSupbQuote(BigDecimal supbQuote) {
        this.supbQuote = supbQuote;
    }

    public QuotationHistory supbQuote(BigDecimal supbQuote) {
        setSupbQuote(supbQuote);
        return this;
    }
    // -- [supcQuote] ------------------------

    @Digits(integer = 11, fraction = 4)
    @Column(name = "supc_quote", precision = 15, scale = 4)
    public BigDecimal getSupcQuote() {
        return supcQuote;
    }

    public void setSupcQuote(BigDecimal supcQuote) {
        this.supcQuote = supcQuote;
    }

    public QuotationHistory supcQuote(BigDecimal supcQuote) {
        setSupcQuote(supcQuote);
        return this;
    }
    // -- [loginName] ------------------------

    @Size(max = 256)
    @Column(name = "login_name", length = 256)
    public String getLoginName() {
        return loginName;
    }

    public void setLoginName(String loginName) {
        this.loginName = loginName;
    }

    public QuotationHistory loginName(String loginName) {
        setLoginName(loginName);
        return this;
    }
    // -- [productCode] ------------------------

    @Size(max = 256)
    @Column(name = "product_code", length = 256)
    public String getProductCode() {
        return productCode;
    }

    public void setProductCode(String productCode) {
        this.productCode = productCode;
    }

    public QuotationHistory productCode(String productCode) {
        setProductCode(productCode);
        return this;
    }
    // -- [orderQuantity] ------------------------

    @Digits(integer = 10, fraction = 0)
    @Column(name = "order_quantity", precision = 10)
    public Integer getOrderQuantity() {
        return orderQuantity;
    }

    public void setOrderQuantity(Integer orderQuantity) {
        this.orderQuantity = orderQuantity;
    }

    public QuotationHistory orderQuantity(Integer orderQuantity) {
        setOrderQuantity(orderQuantity);
        return this;
    }
    // -- [procBy] ------------------------

    /**
     * 多处理线程时每个线程标识
     */
    @Size(max = 255)
    @Column(name = "proc_by")
    public String getProcBy() {
        return procBy;
    }

    public void setProcBy(String procBy) {
        this.procBy = procBy;
    }

    public QuotationHistory procBy(String procBy) {
        setProcBy(procBy);
        return this;
    }
    // -- [procFlag] ------------------------

    /**
     * 处理标记 1：已完成 0：未完成
     */
    @Column(name = "proc_flag", length = 0)
    public Boolean getProcFlag() {
        return procFlag;
    }

    public void setProcFlag(Boolean procFlag) {
        this.procFlag = procFlag;
    }

    public QuotationHistory procFlag(Boolean procFlag) {
        setProcFlag(procFlag);
        return this;
    }

    /**
     * Apply the default values.
     */
    public QuotationHistory withDefaults() {
        setMiProductQuote(new BigDecimal("0.0000"));
        setAtProductQuote(new BigDecimal("0.0000"));
        setFactoryQuote(new BigDecimal("0.0000"));
        setUniQuote(new BigDecimal("0.0000"));
        setSupaQuote(new BigDecimal("0.0000"));
        setSupbQuote(new BigDecimal("0.0000"));
        setSupcQuote(new BigDecimal("0.0000"));
        return this;
    }

    /**
     * Equals implementation using a business key.
     */
    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof QuotationHistory && hashCode() == other.hashCode());
    }


    /**
     * Construct a readable string representation for this QuotationHistory instance.
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this) //
                .add("id", getId()) //
                .add("atProductCode", getAtProductCode()) //
                .add("atProductName", getAtProductName()) //
                .add("atProductDesc", getAtProductDesc()) //
                .add("miProductName", getMiProductName()) //
                .add("miProductCode", getMiProductCode()) //
                .add("miProductDesc", getMiProductDesc()) //
                .add("miProductQuote", getMiProductQuote()) //
                .add("atProductQuote", getAtProductQuote()) //
                .add("factoryQuote", getFactoryQuote()) //
                .add("uniQuote", getUniQuote()) //
                .add("supaQuote", getSupaQuote()) //
                .add("supbQuote", getSupbQuote()) //
                .add("supcQuote", getSupcQuote()) //
                .add("loginName", getLoginName()) //
                .add("productCode", getProductCode()) //
                .add("orderQuantity", getOrderQuantity()) //
                .add("procBy", getProcBy()) //
                .add("procFlag", getProcFlag()) //
                .toString();
    }
}