/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-angular:src/main/java/domain/EntityMeta_.java.e.vm
 */
package com.sadetec.model;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@StaticMetamodel(QuotationLog.class)
public abstract class QuotationLog_ {

    // Raw attributes
    public static volatile SingularAttribute<QuotationLog, Integer> id;
    public static volatile SingularAttribute<QuotationLog, String> atProductCode;
    public static volatile SingularAttribute<QuotationLog, String> atProductName;
    public static volatile SingularAttribute<QuotationLog, String> atProductDesc;
    public static volatile SingularAttribute<QuotationLog, String> miProductName;
    public static volatile SingularAttribute<QuotationLog, String> miProductCode;
    public static volatile SingularAttribute<QuotationLog, String> miProductDesc;
    public static volatile SingularAttribute<QuotationLog, BigDecimal> miProductQuote;
    public static volatile SingularAttribute<QuotationLog, BigDecimal> atProductQuote;
    public static volatile SingularAttribute<QuotationLog, BigDecimal> factoryQuote;
    public static volatile SingularAttribute<QuotationLog, BigDecimal> uniQuote;
    public static volatile SingularAttribute<QuotationLog, BigDecimal> supaQuote;
    public static volatile SingularAttribute<QuotationLog, BigDecimal> supbQuote;
    public static volatile SingularAttribute<QuotationLog, BigDecimal> supcQuote;
    public static volatile SingularAttribute<QuotationLog, String> loginName;
    public static volatile SingularAttribute<QuotationLog, Integer> orderQuantity;
    public static volatile SingularAttribute<QuotationLog, String> name;
    public static volatile SingularAttribute<QuotationLog, LocalDateTime> quotationTime;
}