/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-angular:src/main/java/domain/EntityMeta_.java.e.vm
 */
package com.sadetec.model;

import java.math.BigDecimal;

import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@StaticMetamodel(QuotationHistory.class)
public abstract class QuotationHistory_ {

    // Raw attributes
    public static volatile SingularAttribute<QuotationHistory, String> id;
    public static volatile SingularAttribute<QuotationHistory, String> atProductName;
    public static volatile SingularAttribute<QuotationHistory, String> atProductDesc;
    public static volatile SingularAttribute<QuotationHistory, String> miProductName;
    public static volatile SingularAttribute<QuotationHistory, String> miProductCode;
    public static volatile SingularAttribute<QuotationHistory, String> miProductDesc;
    public static volatile SingularAttribute<QuotationHistory, BigDecimal> miProductQuote;
    public static volatile SingularAttribute<QuotationHistory, BigDecimal> atProductQuote;
    public static volatile SingularAttribute<QuotationHistory, BigDecimal> factoryQuote;
    public static volatile SingularAttribute<QuotationHistory, BigDecimal> uniQuote;
    public static volatile SingularAttribute<QuotationHistory, BigDecimal> supaQuote;
    public static volatile SingularAttribute<QuotationHistory, BigDecimal> supbQuote;
    public static volatile SingularAttribute<QuotationHistory, BigDecimal> supcQuote;
    public static volatile SingularAttribute<QuotationHistory, String> loginName;
    public static volatile SingularAttribute<QuotationHistory, String> productCode;
    public static volatile SingularAttribute<QuotationHistory, Integer> orderQuantity;
    public static volatile SingularAttribute<QuotationHistory, String> procBy;
    public static volatile SingularAttribute<QuotationHistory, Boolean> procFlag;
}