/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-angular:src/main/java/domain/EntityMeta_.java.e.vm
 */
package com.sadetec.model;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@StaticMetamodel(ResPartner.class)
public abstract class ResPartner_ {

    // Raw attributes
    public static volatile SingularAttribute<ResPartner, Integer> id;
    public static volatile SingularAttribute<ResPartner, String> name;
    public static volatile SingularAttribute<ResPartner, String> displayName;
    public static volatile SingularAttribute<ResPartner, Integer> companyId;
    public static volatile SingularAttribute<ResPartner, String> companyName;
    public static volatile SingularAttribute<ResPartner, String> comment;
    public static volatile SingularAttribute<ResPartner, String> website;
    public static volatile SingularAttribute<ResPartner, String> email;
    public static volatile SingularAttribute<ResPartner, String> job;
    public static volatile SingularAttribute<ResPartner, LocalDateTime> createDate;
    public static volatile SingularAttribute<ResPartner, Integer> color;
    public static volatile SingularAttribute<ResPartner, Boolean> active;
    public static volatile SingularAttribute<ResPartner, Boolean> isSupplier;
    public static volatile SingularAttribute<ResPartner, Boolean> isCompany;
    public static volatile SingularAttribute<ResPartner, Boolean> isEmployee;
    public static volatile SingularAttribute<ResPartner, Boolean> isCustomer;
    public static volatile SingularAttribute<ResPartner, String> city;
    public static volatile SingularAttribute<ResPartner, String> street;
    public static volatile SingularAttribute<ResPartner, String> zip;
    public static volatile SingularAttribute<ResPartner, String> fax;
    public static volatile SingularAttribute<ResPartner, String> phone;
    public static volatile SingularAttribute<ResPartner, String> mobile;
    public static volatile SingularAttribute<ResPartner, String> title;
    public static volatile SingularAttribute<ResPartner, Integer> countryId;
    public static volatile SingularAttribute<ResPartner, Integer> parentId;
    public static volatile SingularAttribute<ResPartner, String> userId;
    public static volatile SingularAttribute<ResPartner, BigDecimal> creditLimit;
    public static volatile SingularAttribute<ResPartner, String> invoiceWarn;
    public static volatile SingularAttribute<ResPartner, String> invoiceWarnMsg;
    public static volatile SingularAttribute<ResPartner, String> pickingWarn;
    public static volatile SingularAttribute<ResPartner, String> pickingWarnMsg;
    public static volatile SingularAttribute<ResPartner, String> purchaseWarn;
    public static volatile SingularAttribute<ResPartner, String> purchaseWarnMsg;
}