/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-angular:src/main/java/domain/Entity.java.e.vm
 */
package com.sadetec.model;

import static javax.persistence.GenerationType.IDENTITY;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.logging.Logger;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.Digits;
import javax.validation.constraints.Size;

import org.hibernate.validator.constraints.Email;

import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;

@Entity
@Table(name = "res_partner")
public class ResPartner implements Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = Logger.getLogger(ResPartner.class.getName());

    // Raw attributes
    private Integer id;
    private String name;
    private String displayName;
    private Integer companyId;
    private String companyName;
    private String comment;
    private String website;
    private String email;
    private String job;
    private LocalDateTime createDate;
    private Integer color;
    private Boolean active;
    private Boolean isSupplier;
    private Boolean isCompany;
    private Boolean isEmployee;
    private Boolean isCustomer;
    private String city;
    private String street;
    private String zip;
    private String fax;
    private String phone;
    private String mobile;
    private String title;
    private Integer countryId;
    private Integer parentId;
    private String userId;
    private BigDecimal creditLimit;
    private String invoiceWarn;
    private String invoiceWarnMsg;
    private String pickingWarn;
    private String pickingWarnMsg;
    private String purchaseWarn;
    private String purchaseWarnMsg;

    public String entityClassName() {
        return ResPartner.class.getSimpleName();
    }

    // -- [id] ------------------------

    @Column(name = "id", precision = 10)
    @GeneratedValue(strategy = IDENTITY)
    @Id
    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public ResPartner id(Integer id) {
        setId(id);
        return this;
    }

    @Transient
    public boolean isIdSet() {
        return id != null;
    }
    // -- [name] ------------------------

    /**
     * 名称
     */
    @Size(max = 256)
    @Column(name = "name", length = 256)
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public ResPartner name(String name) {
        setName(name);
        return this;
    }
    // -- [displayName] ------------------------

    /**
     * 显示名称
     */
    @Size(max = 256)
    @Column(name = "display_name", length = 256)
    public String getDisplayName() {
        return displayName;
    }

    public void setDisplayName(String displayName) {
        this.displayName = displayName;
    }

    public ResPartner displayName(String displayName) {
        setDisplayName(displayName);
        return this;
    }
    // -- [companyId] ------------------------

    /**
     * 公司ID
     */
    @Digits(integer = 10, fraction = 0)
    @Column(name = "company_id", precision = 10)
    public Integer getCompanyId() {
        return companyId;
    }

    public void setCompanyId(Integer companyId) {
        this.companyId = companyId;
    }

    public ResPartner companyId(Integer companyId) {
        setCompanyId(companyId);
        return this;
    }
    // -- [companyName] ------------------------

    /**
     * 公司名称
     */
    @Size(max = 256)
    @Column(name = "company_name", length = 256)
    public String getCompanyName() {
        return companyName;
    }

    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }

    public ResPartner companyName(String companyName) {
        setCompanyName(companyName);
        return this;
    }
    // -- [comment] ------------------------

    /**
     * 备注
     */
    @Size(max = 65535)
    @Column(name = "`comment`", length = 65535)
    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    public ResPartner comment(String comment) {
        setComment(comment);
        return this;
    }
    // -- [website] ------------------------

    /**
     * 网址
     */
    @Size(max = 512)
    @Column(name = "website", length = 512)
    public String getWebsite() {
        return website;
    }

    public void setWebsite(String website) {
        this.website = website;
    }

    public ResPartner website(String website) {
        setWebsite(website);
        return this;
    }
    // -- [email] ------------------------

    /**
     * 邮箱
     */
    @Email
    @Size(max = 128)
    @Column(name = "email", length = 128)
    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public ResPartner email(String email) {
        setEmail(email);
        return this;
    }
    // -- [job] ------------------------

    /**
     * 职务
     */
    @Size(max = 128)
    @Column(name = "job", length = 128)
    public String getJob() {
        return job;
    }

    public void setJob(String job) {
        this.job = job;
    }

    public ResPartner job(String job) {
        setJob(job);
        return this;
    }
    // -- [createDate] ------------------------

    /**
     * 创建日期
     */
    @Column(name = "create_date", length = 19)
    public LocalDateTime getCreateDate() {
        return createDate;
    }

    public void setCreateDate(LocalDateTime createDate) {
        this.createDate = createDate;
    }

    public ResPartner createDate(LocalDateTime createDate) {
        setCreateDate(createDate);
        return this;
    }
    // -- [color] ------------------------

    /**
     * 颜色索引
     */
    @Digits(integer = 10, fraction = 0)
    @Column(name = "color", precision = 10)
    public Integer getColor() {
        return color;
    }

    public void setColor(Integer color) {
        this.color = color;
    }

    public ResPartner color(Integer color) {
        setColor(color);
        return this;
    }
    // -- [active] ------------------------

    /**
     * 活动
     */
    @Column(name = "active", length = 0)
    public Boolean getActive() {
        return active;
    }

    public void setActive(Boolean active) {
        this.active = active;
    }

    public ResPartner active(Boolean active) {
        setActive(active);
        return this;
    }
    // -- [isSupplier] ------------------------

    /**
     * 供应商
     */
    @Column(name = "is_supplier", length = 0)
    public Boolean getIsSupplier() {
        return isSupplier;
    }

    public void setIsSupplier(Boolean isSupplier) {
        this.isSupplier = isSupplier;
    }

    public ResPartner isSupplier(Boolean isSupplier) {
        setIsSupplier(isSupplier);
        return this;
    }
    // -- [isCompany] ------------------------

    /**
     * 公司
     */
    @Column(name = "is_company", length = 0)
    public Boolean getIsCompany() {
        return isCompany;
    }

    public void setIsCompany(Boolean isCompany) {
        this.isCompany = isCompany;
    }

    public ResPartner isCompany(Boolean isCompany) {
        setIsCompany(isCompany);
        return this;
    }
    // -- [isEmployee] ------------------------

    /**
     * 员工
     */
    @Column(name = "is_employee", length = 0)
    public Boolean getIsEmployee() {
        return isEmployee;
    }

    public void setIsEmployee(Boolean isEmployee) {
        this.isEmployee = isEmployee;
    }

    public ResPartner isEmployee(Boolean isEmployee) {
        setIsEmployee(isEmployee);
        return this;
    }
    // -- [isCustomer] ------------------------

    /**
     * 客户
     */
    @Column(name = "is_customer", length = 0)
    public Boolean getIsCustomer() {
        return isCustomer;
    }

    public void setIsCustomer(Boolean isCustomer) {
        this.isCustomer = isCustomer;
    }

    public ResPartner isCustomer(Boolean isCustomer) {
        setIsCustomer(isCustomer);
        return this;
    }
    // -- [city] ------------------------

    /**
     * 城市
     */
    @Size(max = 64)
    @Column(name = "city", length = 64)
    public String getCity() {
        return city;
    }

    public void setCity(String city) {
        this.city = city;
    }

    public ResPartner city(String city) {
        setCity(city);
        return this;
    }
    // -- [street] ------------------------

    /**
     * 街道
     */
    @Size(max = 256)
    @Column(name = "street", length = 256)
    public String getStreet() {
        return street;
    }

    public void setStreet(String street) {
        this.street = street;
    }

    public ResPartner street(String street) {
        setStreet(street);
        return this;
    }
    // -- [zip] ------------------------

    /**
     * 邮编
     */
    @Size(max = 64)
    @Column(name = "zip", length = 64)
    public String getZip() {
        return zip;
    }

    public void setZip(String zip) {
        this.zip = zip;
    }

    public ResPartner zip(String zip) {
        setZip(zip);
        return this;
    }
    // -- [fax] ------------------------

    /**
     * 传真
     */
    @Size(max = 64)
    @Column(name = "fax", length = 64)
    public String getFax() {
        return fax;
    }

    public void setFax(String fax) {
        this.fax = fax;
    }

    public ResPartner fax(String fax) {
        setFax(fax);
        return this;
    }
    // -- [phone] ------------------------

    /**
     * 电话
     */
    @Size(max = 64)
    @Column(name = "phone", length = 64)
    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public ResPartner phone(String phone) {
        setPhone(phone);
        return this;
    }
    // -- [mobile] ------------------------

    /**
     * 手机
     */
    @Size(max = 64)
    @Column(name = "mobile", length = 64)
    public String getMobile() {
        return mobile;
    }

    public void setMobile(String mobile) {
        this.mobile = mobile;
    }

    public ResPartner mobile(String mobile) {
        setMobile(mobile);
        return this;
    }
    // -- [title] ------------------------

    /**
     * 称呼：女士、先生
     */
    @Size(max = 64)
    @Column(name = "title", length = 64)
    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public ResPartner title(String title) {
        setTitle(title);
        return this;
    }
    // -- [countryId] ------------------------

    /**
     * 国家
     */
    @Digits(integer = 10, fraction = 0)
    @Column(name = "country_id", precision = 10)
    public Integer getCountryId() {
        return countryId;
    }

    public void setCountryId(Integer countryId) {
        this.countryId = countryId;
    }

    public ResPartner countryId(Integer countryId) {
        setCountryId(countryId);
        return this;
    }
    // -- [parentId] ------------------------

    /**
     * 上级标识
     */
    @Digits(integer = 10, fraction = 0)
    @Column(name = "parent_id", precision = 10)
    public Integer getParentId() {
        return parentId;
    }

    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    public ResPartner parentId(Integer parentId) {
        setParentId(parentId);
        return this;
    }
    // -- [userId] ------------------------

    /**
     * 关联销售
     */
    @Size(max = 64)
    @Column(name = "user_id", length = 64)
    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public ResPartner userId(String userId) {
        setUserId(userId);
        return this;
    }
    // -- [creditLimit] ------------------------

    /**
     * 授信额度
     */
    @Digits(integer = 11, fraction = 4)
    @Column(name = "credit_limit", precision = 15, scale = 4)
    public BigDecimal getCreditLimit() {
        return creditLimit;
    }

    public void setCreditLimit(BigDecimal creditLimit) {
        this.creditLimit = creditLimit;
    }

    public ResPartner creditLimit(BigDecimal creditLimit) {
        setCreditLimit(creditLimit);
        return this;
    }
    // -- [invoiceWarn] ------------------------

    /**
     * 发票
     */
    @Size(max = 64)
    @Column(name = "invoice_warn", length = 64)
    public String getInvoiceWarn() {
        return invoiceWarn;
    }

    public void setInvoiceWarn(String invoiceWarn) {
        this.invoiceWarn = invoiceWarn;
    }

    public ResPartner invoiceWarn(String invoiceWarn) {
        setInvoiceWarn(invoiceWarn);
        return this;
    }
    // -- [invoiceWarnMsg] ------------------------

    /**
     * 发票消息
     */
    @Size(max = 65535)
    @Column(name = "invoice_warn_msg", length = 65535)
    public String getInvoiceWarnMsg() {
        return invoiceWarnMsg;
    }

    public void setInvoiceWarnMsg(String invoiceWarnMsg) {
        this.invoiceWarnMsg = invoiceWarnMsg;
    }

    public ResPartner invoiceWarnMsg(String invoiceWarnMsg) {
        setInvoiceWarnMsg(invoiceWarnMsg);
        return this;
    }
    // -- [pickingWarn] ------------------------

    /**
     * 出库
     */
    @Size(max = 64)
    @Column(name = "picking_warn", length = 64)
    public String getPickingWarn() {
        return pickingWarn;
    }

    public void setPickingWarn(String pickingWarn) {
        this.pickingWarn = pickingWarn;
    }

    public ResPartner pickingWarn(String pickingWarn) {
        setPickingWarn(pickingWarn);
        return this;
    }
    // -- [pickingWarnMsg] ------------------------

    /**
     * 出库通知
     */
    @Size(max = 65535)
    @Column(name = "picking_warn_msg", length = 65535)
    public String getPickingWarnMsg() {
        return pickingWarnMsg;
    }

    public void setPickingWarnMsg(String pickingWarnMsg) {
        this.pickingWarnMsg = pickingWarnMsg;
    }

    public ResPartner pickingWarnMsg(String pickingWarnMsg) {
        setPickingWarnMsg(pickingWarnMsg);
        return this;
    }
    // -- [purchaseWarn] ------------------------

    /**
     * 采购
     */
    @Size(max = 64)
    @Column(name = "purchase_warn", length = 64)
    public String getPurchaseWarn() {
        return purchaseWarn;
    }

    public void setPurchaseWarn(String purchaseWarn) {
        this.purchaseWarn = purchaseWarn;
    }

    public ResPartner purchaseWarn(String purchaseWarn) {
        setPurchaseWarn(purchaseWarn);
        return this;
    }
    // -- [purchaseWarnMsg] ------------------------

    /**
     * 采购消息
     */
    @Size(max = 65535)
    @Column(name = "purchase_warn_msg", length = 65535)
    public String getPurchaseWarnMsg() {
        return purchaseWarnMsg;
    }

    public void setPurchaseWarnMsg(String purchaseWarnMsg) {
        this.purchaseWarnMsg = purchaseWarnMsg;
    }

    public ResPartner purchaseWarnMsg(String purchaseWarnMsg) {
        setPurchaseWarnMsg(purchaseWarnMsg);
        return this;
    }

    /**
     * Apply the default values.
     */
    public ResPartner withDefaults() {
        setCreditLimit(new BigDecimal("0.0000"));
        return this;
    }

    /**
     * Equals implementation using a business key.
     */
    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof ResPartner && hashCode() == other.hashCode());
    }


    /**
     * Construct a readable string representation for this ResPartner instance.
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this) //
                .add("id", getId()) //
                .add("name", getName()) //
                .add("displayName", getDisplayName()) //
                .add("companyId", getCompanyId()) //
                .add("companyName", getCompanyName()) //
                .add("comment", getComment()) //
                .add("website", getWebsite()) //
                .add("email", getEmail()) //
                .add("job", getJob()) //
                .add("createDate", getCreateDate()) //
                .add("color", getColor()) //
                .add("active", getActive()) //
                .add("isSupplier", getIsSupplier()) //
                .add("isCompany", getIsCompany()) //
                .add("isEmployee", getIsEmployee()) //
                .add("isCustomer", getIsCustomer()) //
                .add("city", getCity()) //
                .add("street", getStreet()) //
                .add("zip", getZip()) //
                .add("fax", getFax()) //
                .add("phone", getPhone()) //
                .add("mobile", getMobile()) //
                .add("title", getTitle()) //
                .add("countryId", getCountryId()) //
                .add("parentId", getParentId()) //
                .add("userId", getUserId()) //
                .add("creditLimit", getCreditLimit()) //
                .add("invoiceWarn", getInvoiceWarn()) //
                .add("invoiceWarnMsg", getInvoiceWarnMsg()) //
                .add("pickingWarn", getPickingWarn()) //
                .add("pickingWarnMsg", getPickingWarnMsg()) //
                .add("purchaseWarn", getPurchaseWarn()) //
                .add("purchaseWarnMsg", getPurchaseWarnMsg()) //
                .toString();
    }
}