/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-angular:src/main/java/domain/EntityMeta_.java.e.vm
 */
package com.sadetec.model;

import java.math.BigDecimal;
import java.util.Date;

import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@StaticMetamodel(SalesOrder.class)
public abstract class SalesOrder_ {

    // Raw attributes
    public static volatile SingularAttribute<SalesOrder, Integer> id;
    public static volatile SingularAttribute<SalesOrder, Integer> formInstanceId;
    public static volatile SingularAttribute<SalesOrder, String> categoryCode;
    public static volatile SingularAttribute<SalesOrder, String> categoryName;
    public static volatile SingularAttribute<SalesOrder, String> seriesCode;
    public static volatile SingularAttribute<SalesOrder, String> seriesName;
    public static volatile SingularAttribute<SalesOrder, String> productCode;
    public static volatile SingularAttribute<SalesOrder, String> productName;
    public static volatile SingularAttribute<SalesOrder, String> processType;
    public static volatile SingularAttribute<SalesOrder, Date> deliveryDate;
    public static volatile SingularAttribute<SalesOrder, Integer> amount;
    public static volatile SingularAttribute<SalesOrder, String> unit;
    public static volatile SingularAttribute<SalesOrder, BigDecimal> factoryPrice;
    public static volatile SingularAttribute<SalesOrder, BigDecimal> costPrice;
    public static volatile SingularAttribute<SalesOrder, BigDecimal> unitPrice;
    public static volatile SingularAttribute<SalesOrder, String> quoterId;
    public static volatile SingularAttribute<SalesOrder, String> quoterName;
    public static volatile SingularAttribute<SalesOrder, String> auditorId;
    public static volatile SingularAttribute<SalesOrder, String> auditorName;
    public static volatile SingularAttribute<SalesOrder, String> drawingUrl;
    public static volatile SingularAttribute<SalesOrder, String> atProductCode;
    public static volatile SingularAttribute<SalesOrder, String> brand;
    public static volatile SingularAttribute<SalesOrder, Boolean> needProc;
    public static volatile SingularAttribute<SalesOrder, String> comment;
    
}