/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-angular:src/main/java/domain/Entity.java.e.vm
 */
package com.sadetec.model;

import static javax.persistence.GenerationType.IDENTITY;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.Date;
import java.util.logging.Logger;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.Transient;
import javax.validation.constraints.Digits;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

import org.springframework.format.annotation.DateTimeFormat;

import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;

@Entity
@Table(name = "sales_order")
public class SalesOrder implements Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = Logger.getLogger(SalesOrder.class.getName());

    // Raw attributes
    private Integer id;
    private Integer formInstanceId;
    private String categoryCode;
    private String categoryName;
    private String seriesCode;
    private String seriesName;
    private String productCode;
    private String productName;
    private String processType;
    
	@Temporal(TemporalType.TIMESTAMP)
	@DateTimeFormat(style = "S-")
    private Date deliveryDate;
	
    private Integer amount;
    private String unit;
    private BigDecimal unitPrice;
    private String comment;

    public String entityClassName() {
        return SalesOrder.class.getSimpleName();
    }

    // -- [id] ------------------------

    @Column(name = "id", precision = 10)
    @GeneratedValue(strategy = IDENTITY)
    @Id
    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public SalesOrder id(Integer id) {
        setId(id);
        return this;
    }

    @Transient
    public boolean isIdSet() {
        return id != null;
    }
    // -- [formInstanceId] ------------------------

    @Digits(integer = 10, fraction = 0)
    @NotNull
    @Column(name = "form_instance_id", nullable = false, precision = 10)
    public Integer getFormInstanceId() {
        return formInstanceId;
    }

    public void setFormInstanceId(Integer formInstanceId) {
        this.formInstanceId = formInstanceId;
    }

    public SalesOrder formInstanceId(Integer formInstanceId) {
        setFormInstanceId(formInstanceId);
        return this;
    }
    // -- [categoryCode] ------------------------

    @Size(max = 256)
    @Column(name = "category_code", length = 256)
    public String getCategoryCode() {
        return categoryCode;
    }

    public void setCategoryCode(String categoryCode) {
        this.categoryCode = categoryCode;
    }

    public SalesOrder categoryCode(String categoryCode) {
        setCategoryCode(categoryCode);
        return this;
    }
    // -- [categoryName] ------------------------

    @Size(max = 256)
    @Column(name = "category_name", length = 256)
    public String getCategoryName() {
        return categoryName;
    }

    public void setCategoryName(String categoryName) {
        this.categoryName = categoryName;
    }

    public SalesOrder categoryName(String categoryName) {
        setCategoryName(categoryName);
        return this;
    }
    // -- [seriesCode] ------------------------

    @Size(max = 256)
    @Column(name = "series_code", length = 256)
    public String getSeriesCode() {
        return seriesCode;
    }

    public void setSeriesCode(String seriesCode) {
        this.seriesCode = seriesCode;
    }

    public SalesOrder seriesCode(String seriesCode) {
        setSeriesCode(seriesCode);
        return this;
    }
    // -- [seriesName] ------------------------

    @Size(max = 256)
    @Column(name = "series_name", length = 256)
    public String getSeriesName() {
        return seriesName;
    }

    public void setSeriesName(String seriesName) {
        this.seriesName = seriesName;
    }

    public SalesOrder seriesName(String seriesName) {
        setSeriesName(seriesName);
        return this;
    }
    // -- [productCode] ------------------------

    @Size(max = 256)
    @Column(name = "product_code", length = 256)
    public String getProductCode() {
        return productCode;
    }

    public void setProductCode(String productCode) {
        this.productCode = productCode;
    }

    public SalesOrder productCode(String productCode) {
        setProductCode(productCode);
        return this;
    }
    // -- [productName] ------------------------

    @Size(max = 256)
    @Column(name = "product_name", length = 256)
    public String getProductName() {
        return productName;
    }

    public void setProductName(String productName) {
        this.productName = productName;
    }

    public SalesOrder productName(String productName) {
        setProductName(productName);
        return this;
    }
    // -- [processType] ------------------------

    @Size(max = 256)
    @Column(name = "process_type", length = 256)
    public String getProcessType() {
        return processType;
    }

    public void setProcessType(String processType) {
        this.processType = processType;
    }

    public SalesOrder processType(String processType) {
        setProcessType(processType);
        return this;
    }
    
    @Digits(integer = 11, fraction = 4)
    @Column(name = "unit_price", precision = 15, scale = 4)
    public BigDecimal getUnitPrice() {
        return unitPrice;
    }

    public void setUnitPrice(BigDecimal unitPrice) {
        this.unitPrice = unitPrice;
    }
    
    @Size(max = 64)
    @Column(name = "unit", length = 64)
    public String getUnit() {
        return unit;
    }

    public void setUnit(String unit) {
        this.unit = unit;
    }
    // -- [deliveryDate] ------------------------

    @Column(name = "delivery_date", length = 19)
    public Date getDeliveryDate() {
        return deliveryDate;
    }

    public void setDeliveryDate(Date deliveryDate) {
        this.deliveryDate = deliveryDate;
    }

    public SalesOrder deliveryDate(Date deliveryDate) {
        setDeliveryDate(deliveryDate);
        return this;
    }
    // -- [amount] ------------------------

    @Digits(integer = 10, fraction = 0)
    @Column(name = "amount", precision = 10)
    public Integer getAmount() {
        return amount;
    }

    public void setAmount(Integer amount) {
        this.amount = amount;
    }

    public SalesOrder amount(Integer amount) {
        setAmount(amount);
        return this;
    }
    // -- [comment] ------------------------

    @Size(max = 512)
    @Column(name = "`comment`", length = 512)
    public String getComment() {
        return comment;
    }

    public void setComment(String comment) {
        this.comment = comment;
    }

    public SalesOrder comment(String comment) {
        setComment(comment);
        return this;
    }

    /**
     * Apply the default values.
     */
    public SalesOrder withDefaults() {
        return this;
    }

    /**
     * Equals implementation using a business key.
     */
    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof SalesOrder && hashCode() == other.hashCode());
    }


    /**
     * Construct a readable string representation for this SalesOrder instance.
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this) //
                .add("id", getId()) //
                .add("formInstanceId", getFormInstanceId()) //
                .add("categoryCode", getCategoryCode()) //
                .add("categoryName", getCategoryName()) //
                .add("seriesCode", getSeriesCode()) //
                .add("seriesName", getSeriesName()) //
                .add("productCode", getProductCode()) //
                .add("productName", getProductName()) //
                .add("processType", getProcessType()) //
                .add("deliveryDate", getDeliveryDate()) //
                .add("amount", getAmount()) //
                .add("comment", getComment()) //
                .toString();
    }
}