/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-angular:src/main/java/domain/EntityMeta_.java.e.vm
 */
package com.sadetec.model;

import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@StaticMetamodel(SeriesSpec.class)
public abstract class SeriesSpec_ {

    // Raw attributes
    public static volatile SingularAttribute<SeriesSpec, Integer> id;
    public static volatile SingularAttribute<SeriesSpec, String> seriesCode;
    public static volatile SingularAttribute<SeriesSpec, String> key;
    public static volatile SingularAttribute<SeriesSpec, String> title;
    public static volatile SingularAttribute<SeriesSpec, String> unit;
    public static volatile SingularAttribute<SeriesSpec, String> propertyCode;
    public static volatile SingularAttribute<SeriesSpec, String> aryChoiceName;
    public static volatile SingularAttribute<SeriesSpec, String> aryChoiceCode;
    public static volatile SingularAttribute<SeriesSpec, String> isUniform;
    public static volatile SingularAttribute<SeriesSpec, String> uniformChoiceCode;
    public static volatile SingularAttribute<SeriesSpec, String> aryIsNull;
    public static volatile SingularAttribute<SeriesSpec, String> valueType;
    public static volatile SingularAttribute<SeriesSpec, String> seriesSpecNo;
    public static volatile SingularAttribute<SeriesSpec, String> singleChoiceName;
    public static volatile SingularAttribute<SeriesSpec, String> hasParamSpec;
    public static volatile SingularAttribute<SeriesSpec, String> displayPattern;
    public static volatile SingularAttribute<SeriesSpec, String> isSpecInch;
    public static volatile SingularAttribute<SeriesSpec, String> closeflag;
}