/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-angular:src/main/java/domain/Entity.java.e.vm
 */
package com.sadetec.model;

import static javax.persistence.GenerationType.IDENTITY;

import java.io.Serializable;
import java.util.logging.Logger;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.Size;

import org.hibernate.validator.constraints.NotEmpty;

import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;

@Entity
@Table(name = "series_spec")
public class SeriesSpec implements Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = Logger.getLogger(SeriesSpec.class.getName());

    // Raw attributes
    private Integer id;
    private String seriesCode;
    private String key;
    private String title;
    private String unit;
    private String propertyCode;
    private String aryChoiceName;
    private String aryChoiceCode;
    private String isUniform;
    private String uniformChoiceCode;
    private String aryIsNull;
    private String valueType;
    private String seriesSpecNo;
    private String singleChoiceName;
    private String hasParamSpec;
    private String displayPattern;
    private String isSpecInch;
    private String closeflag;

    public String entityClassName() {
        return SeriesSpec.class.getSimpleName();
    }

    // -- [id] ------------------------

    @Column(name = "id", precision = 10)
    @GeneratedValue(strategy = IDENTITY)
    @Id
    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public SeriesSpec id(Integer id) {
        setId(id);
        return this;
    }

    @Transient
    public boolean isIdSet() {
        return id != null;
    }
    // -- [seriesCode] ------------------------

    @NotEmpty
    @Size(max = 128)
    @Column(name = "series_code", nullable = false, length = 128)
    public String getSeriesCode() {
        return seriesCode;
    }

    public void setSeriesCode(String seriesCode) {
        this.seriesCode = seriesCode;
    }

    public SeriesSpec seriesCode(String seriesCode) {
        setSeriesCode(seriesCode);
        return this;
    }
    // -- [key] ------------------------

    @NotEmpty
    @Size(max = 64)
    @Column(name = "`key`", nullable = false, length = 64)
    public String getKey() {
        return key;
    }

    public void setKey(String key) {
        this.key = key;
    }

    public SeriesSpec key(String key) {
        setKey(key);
        return this;
    }
    // -- [title] ------------------------

    @Size(max = 256)
    @Column(name = "title", length = 256)
    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public SeriesSpec title(String title) {
        setTitle(title);
        return this;
    }
    // -- [unit] ------------------------

    @Size(max = 512)
    @Column(name = "unit", length = 512)
    public String getUnit() {
        return unit;
    }

    public void setUnit(String unit) {
        this.unit = unit;
    }

    public SeriesSpec unit(String unit) {
        setUnit(unit);
        return this;
    }
    // -- [propertyCode] ------------------------

    @Size(max = 512)
    @Column(name = "property_code", length = 512)
    public String getPropertyCode() {
        return propertyCode;
    }

    public void setPropertyCode(String propertyCode) {
        this.propertyCode = propertyCode;
    }

    public SeriesSpec propertyCode(String propertyCode) {
        setPropertyCode(propertyCode);
        return this;
    }
    // -- [aryChoiceName] ------------------------

    @Size(max = 65535)
    @Column(name = "ary_choice_name", length = 65535)
    public String getAryChoiceName() {
        return aryChoiceName;
    }

    public void setAryChoiceName(String aryChoiceName) {
        this.aryChoiceName = aryChoiceName;
    }

    public SeriesSpec aryChoiceName(String aryChoiceName) {
        setAryChoiceName(aryChoiceName);
        return this;
    }
    // -- [aryChoiceCode] ------------------------

    @Size(max = 65535)
    @Column(name = "ary_choice_code", length = 65535)
    public String getAryChoiceCode() {
        return aryChoiceCode;
    }

    public void setAryChoiceCode(String aryChoiceCode) {
        this.aryChoiceCode = aryChoiceCode;
    }

    public SeriesSpec aryChoiceCode(String aryChoiceCode) {
        setAryChoiceCode(aryChoiceCode);
        return this;
    }
    // -- [isUniform] ------------------------

    @Size(max = 256)
    @Column(name = "is_uniform", length = 256)
    public String getIsUniform() {
        return isUniform;
    }

    public void setIsUniform(String isUniform) {
        this.isUniform = isUniform;
    }

    public SeriesSpec isUniform(String isUniform) {
        setIsUniform(isUniform);
        return this;
    }
    // -- [uniformChoiceCode] ------------------------

    @Size(max = 256)
    @Column(name = "uniform_choice_code", length = 256)
    public String getUniformChoiceCode() {
        return uniformChoiceCode;
    }

    public void setUniformChoiceCode(String uniformChoiceCode) {
        this.uniformChoiceCode = uniformChoiceCode;
    }

    public SeriesSpec uniformChoiceCode(String uniformChoiceCode) {
        setUniformChoiceCode(uniformChoiceCode);
        return this;
    }
    // -- [aryIsNull] ------------------------

    @Size(max = 65535)
    @Column(name = "ary_is_null", length = 65535)
    public String getAryIsNull() {
        return aryIsNull;
    }

    public void setAryIsNull(String aryIsNull) {
        this.aryIsNull = aryIsNull;
    }

    public SeriesSpec aryIsNull(String aryIsNull) {
        setAryIsNull(aryIsNull);
        return this;
    }
    // -- [valueType] ------------------------

    @Size(max = 256)
    @Column(name = "value_type", length = 256)
    public String getValueType() {
        return valueType;
    }

    public void setValueType(String valueType) {
        this.valueType = valueType;
    }

    public SeriesSpec valueType(String valueType) {
        setValueType(valueType);
        return this;
    }
    // -- [seriesSpecNo] ------------------------

    @Size(max = 256)
    @Column(name = "series_spec_no", length = 256)
    public String getSeriesSpecNo() {
        return seriesSpecNo;
    }

    public void setSeriesSpecNo(String seriesSpecNo) {
        this.seriesSpecNo = seriesSpecNo;
    }

    public SeriesSpec seriesSpecNo(String seriesSpecNo) {
        setSeriesSpecNo(seriesSpecNo);
        return this;
    }
    // -- [singleChoiceName] ------------------------

    @Size(max = 256)
    @Column(name = "single_choice_name", length = 256)
    public String getSingleChoiceName() {
        return singleChoiceName;
    }

    public void setSingleChoiceName(String singleChoiceName) {
        this.singleChoiceName = singleChoiceName;
    }

    public SeriesSpec singleChoiceName(String singleChoiceName) {
        setSingleChoiceName(singleChoiceName);
        return this;
    }
    // -- [hasParamSpec] ------------------------

    @Size(max = 256)
    @Column(name = "has_param_spec", length = 256)
    public String getHasParamSpec() {
        return hasParamSpec;
    }

    public void setHasParamSpec(String hasParamSpec) {
        this.hasParamSpec = hasParamSpec;
    }

    public SeriesSpec hasParamSpec(String hasParamSpec) {
        setHasParamSpec(hasParamSpec);
        return this;
    }
    // -- [displayPattern] ------------------------

    @Size(max = 256)
    @Column(name = "display_pattern", length = 256)
    public String getDisplayPattern() {
        return displayPattern;
    }

    public void setDisplayPattern(String displayPattern) {
        this.displayPattern = displayPattern;
    }

    public SeriesSpec displayPattern(String displayPattern) {
        setDisplayPattern(displayPattern);
        return this;
    }
    // -- [isSpecInch] ------------------------

    @Size(max = 256)
    @Column(name = "is_spec_inch", length = 256)
    public String getIsSpecInch() {
        return isSpecInch;
    }

    public void setIsSpecInch(String isSpecInch) {
        this.isSpecInch = isSpecInch;
    }

    public SeriesSpec isSpecInch(String isSpecInch) {
        setIsSpecInch(isSpecInch);
        return this;
    }
    // -- [closeflag] ------------------------

    @Size(max = 256)
    @Column(name = "closeflag", length = 256)
    public String getCloseflag() {
        return closeflag;
    }

    public void setCloseflag(String closeflag) {
        this.closeflag = closeflag;
    }

    public SeriesSpec closeflag(String closeflag) {
        setCloseflag(closeflag);
        return this;
    }

    /**
     * Apply the default values.
     */
    public SeriesSpec withDefaults() {
        return this;
    }

    /**
     * Equals implementation using a business key.
     */
    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof SeriesSpec && hashCode() == other.hashCode());
    }

    /**
     * Construct a readable string representation for this SeriesSpec instance.
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this) //
                .add("id", getId()) //
                .add("seriesCode", getSeriesCode()) //
                .add("key", getKey()) //
                .add("title", getTitle()) //
                .add("unit", getUnit()) //
                .add("propertyCode", getPropertyCode()) //
                .add("aryChoiceName", getAryChoiceName()) //
                .add("aryChoiceCode", getAryChoiceCode()) //
                .add("isUniform", getIsUniform()) //
                .add("uniformChoiceCode", getUniformChoiceCode()) //
                .add("aryIsNull", getAryIsNull()) //
                .add("valueType", getValueType()) //
                .add("seriesSpecNo", getSeriesSpecNo()) //
                .add("singleChoiceName", getSingleChoiceName()) //
                .add("hasParamSpec", getHasParamSpec()) //
                .add("displayPattern", getDisplayPattern()) //
                .add("isSpecInch", getIsSpecInch()) //
                .add("closeflag", getCloseflag()) //
                .toString();
    }
}