/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-angular:src/main/java/domain/Entity.java.e.vm
 */
package com.sadetec.model;

import static javax.persistence.GenerationType.IDENTITY;

import java.io.Serializable;
import java.math.BigDecimal;
import java.time.LocalDateTime;
import java.util.logging.Logger;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.Digits;
import javax.validation.constraints.Size;

import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;

@Entity
@Table(name = "stock_quant")
public class StockQuant implements Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = Logger.getLogger(StockQuant.class.getName());

    // Raw attributes
    private Integer id;
    private String productId;
    private BigDecimal qty;
    private BigDecimal useQty;
    private String unit;
    private String createUid;
    private LocalDateTime createDate;
    private BigDecimal cost;
    private Integer propagatedFromId;
    private Integer packageId;
    private Integer lotId;
    private Integer locationId;
    private String lot;
    private String location;
    private Integer reservationId;
    private Integer packagingTypeId;
    private Integer negativeMoveId;
    private LocalDateTime inDate;

    public String entityClassName() {
        return StockQuant.class.getSimpleName();
    }

    // -- [id] ------------------------

    @Column(name = "id", precision = 10)
    @GeneratedValue(strategy = IDENTITY)
    @Id
    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public StockQuant id(Integer id) {
        setId(id);
        return this;
    }

    @Transient
    public boolean isIdSet() {
        return id != null;
    }
    // -- [productId] ------------------------

    /**
     * 产品标识
     */
    @Size(max = 256)
    @Column(name = "product_id", length = 256)
    public String getProductId() {
        return productId;
    }

    public void setProductId(String productId) {
        this.productId = productId;
    }

    public StockQuant productId(String productId) {
        setProductId(productId);
        return this;
    }
    // -- [qty] ------------------------

    /**
     * 库存数量
     */
    @Digits(integer = 11, fraction = 4)
    @Column(name = "qty", precision = 15, scale = 4)
    public BigDecimal getQty() {
        return qty;
    }

    public void setQty(BigDecimal qty) {
        this.qty = qty;
    }

    public StockQuant qty(BigDecimal qty) {
        setQty(qty);
        return this;
    }
    // -- [useQty] ------------------------

    /**
     * 可用数量
     */
    @Digits(integer = 11, fraction = 4)
    @Column(name = "use_qty", precision = 15, scale = 4)
    public BigDecimal getUseQty() {
        return useQty;
    }

    public void setUseQty(BigDecimal useQty) {
        this.useQty = useQty;
    }

    public StockQuant useQty(BigDecimal useQty) {
        setUseQty(useQty);
        return this;
    }
    
    // -- [unit] ------------------------

    /**
     * 产品标识
     */
    @Size(max = 32)
    @Column(name = "unit", length = 32)
    public String getUnit() {
        return unit;
    }

    public void setUnit(String unit) {
        this.unit = unit;
    }

    public StockQuant unit(String unit) {
        setUnit(unit);
        return this;
    }
    
    // -- [createUid] ------------------------

    /**
     * 添加人
     */
    @Size(max = 64)
    @Column(name = "create_uid", length = 64)
    public String getCreateUid() {
        return createUid;
    }

    public void setCreateUid(String createUid) {
        this.createUid = createUid;
    }

    public StockQuant createUid(String createUid) {
        setCreateUid(createUid);
        return this;
    }
    // -- [createDate] ------------------------

    /**
     * 添加日期
     */
    @Column(name = "create_date", length = 19)
    public LocalDateTime getCreateDate() {
        return createDate;
    }

    public void setCreateDate(LocalDateTime createDate) {
        this.createDate = createDate;
    }

    public StockQuant createDate(LocalDateTime createDate) {
        setCreateDate(createDate);
        return this;
    }
    // -- [cost] ------------------------

    /**
     * 成本
     */
    @Digits(integer = 11, fraction = 4)
    @Column(name = "cost", precision = 15, scale = 4)
    public BigDecimal getCost() {
        return cost;
    }

    public void setCost(BigDecimal cost) {
        this.cost = cost;
    }

    public StockQuant cost(BigDecimal cost) {
        setCost(cost);
        return this;
    }
    // -- [propagatedFromId] ------------------------

    /**
     * Linked Quant
     */
    @Digits(integer = 10, fraction = 0)
    @Column(name = "propagated_from_id", precision = 10)
    public Integer getPropagatedFromId() {
        return propagatedFromId;
    }

    public void setPropagatedFromId(Integer propagatedFromId) {
        this.propagatedFromId = propagatedFromId;
    }

    public StockQuant propagatedFromId(Integer propagatedFromId) {
        setPropagatedFromId(propagatedFromId);
        return this;
    }
    // -- [packageId] ------------------------

    /**
     * Package
     */
    @Digits(integer = 10, fraction = 0)
    @Column(name = "package_id", precision = 10)
    public Integer getPackageId() {
        return packageId;
    }

    public void setPackageId(Integer packageId) {
        this.packageId = packageId;
    }

    public StockQuant packageId(Integer packageId) {
        setPackageId(packageId);
        return this;
    }
    // -- [lotId] ------------------------

    /**
     * Lot/Serial Number
     */
    @Size(max = 32)
    @Column(name = "lot", length = 32)
    public String getLot() {
        return lot;
    }

    public void setLot(String lot) {
        this.lot = lot;
    }

    public StockQuant lot(String lot) {
    	setLot(lot);
        return this;
    }
    
    // -- [lot] ------------------------

    /**
     * Lot/Serial Number
     */
    @Digits(integer = 10, fraction = 0)
    @Column(name = "lot_id", precision = 10)
    public Integer getLotId() {
        return lotId;
    }

    public void setLotId(Integer lotId) {
        this.lotId = lotId;
    }
    
    public StockQuant lotId(Integer lotId) {
    	setLotId(lotId);
        return this;
    }

    // -- [locationId] ------------------------

    /**
     * Location
     */
    @Digits(integer = 10, fraction = 0)
    @Column(name = "location_id", precision = 10)
    public Integer getLocationId() {
        return locationId;
    }

    public void setLocationId(Integer locationId) {
        this.locationId = locationId;
    }

    public StockQuant locationId(Integer locationId) {
        setLocationId(locationId);
        return this;
    }
    
    /**
     * Location
     */
    @Size(max = 64)
    @Column(name = "location", length = 64)
    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }

    public StockQuant location(String location) {
    	setLocation(location);
        return this;
    }
    // -- [reservationId] ------------------------

    /**
     * Reserved for Move
     */
    @Digits(integer = 10, fraction = 0)
    @Column(name = "reservation_id", precision = 10)
    public Integer getReservationId() {
        return reservationId;
    }

    public void setReservationId(Integer reservationId) {
        this.reservationId = reservationId;
    }

    public StockQuant reservationId(Integer reservationId) {
        setReservationId(reservationId);
        return this;
    }
    // -- [packagingTypeId] ------------------------

    /**
     * Type of packaging
     */
    @Digits(integer = 10, fraction = 0)
    @Column(name = "packaging_type_id", precision = 10)
    public Integer getPackagingTypeId() {
        return packagingTypeId;
    }

    public void setPackagingTypeId(Integer packagingTypeId) {
        this.packagingTypeId = packagingTypeId;
    }

    public StockQuant packagingTypeId(Integer packagingTypeId) {
        setPackagingTypeId(packagingTypeId);
        return this;
    }
    // -- [negativeMoveId] ------------------------

    /**
     * Move Negative Quant
     */
    @Digits(integer = 10, fraction = 0)
    @Column(name = "negative_move_id", precision = 10)
    public Integer getNegativeMoveId() {
        return negativeMoveId;
    }

    public void setNegativeMoveId(Integer negativeMoveId) {
        this.negativeMoveId = negativeMoveId;
    }

    public StockQuant negativeMoveId(Integer negativeMoveId) {
        setNegativeMoveId(negativeMoveId);
        return this;
    }
    // -- [inDate] ------------------------

    /**
     * 价格开始日期
     */
    @Column(name = "in_date", length = 19)
    public LocalDateTime getInDate() {
        return inDate;
    }

    public void setInDate(LocalDateTime inDate) {
        this.inDate = inDate;
    }

    public StockQuant inDate(LocalDateTime inDate) {
        setInDate(inDate);
        return this;
    }

    /**
     * Apply the default values.
     */
    public StockQuant withDefaults() {
        setQty(new BigDecimal("0.0000"));
        setUseQty(new BigDecimal("0.0000"));
        setCost(new BigDecimal("0.0000"));
        return this;
    }

    /**
     * Equals implementation using a business key.
     */
    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof StockQuant && hashCode() == other.hashCode());
    }

    /**
     * Construct a readable string representation for this StockQuant instance.
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this) //
                .add("id", getId()) //
                .add("productId", getProductId()) //
                .add("qty", getQty()) //
                .add("useQty", getUseQty()) //
                .add("createUid", getCreateUid()) //
                .add("createDate", getCreateDate()) //
                .add("cost", getCost()) //
                .add("propagatedFromId", getPropagatedFromId()) //
                .add("packageId", getPackageId()) //
                .add("lotId", getLotId()) //
                .add("locationId", getLocationId()) //
                .add("reservationId", getReservationId()) //
                .add("packagingTypeId", getPackagingTypeId()) //
                .add("negativeMoveId", getNegativeMoveId()) //
                .add("inDate", getInDate()) //
                .toString();
    }
}