/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-angular:src/main/java/domain/EntityMeta_.java.e.vm
 */
package com.sadetec.model;

import java.math.BigDecimal;
import java.time.LocalDateTime;

import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@StaticMetamodel(StockQuant.class)
public abstract class StockQuant_ {

    // Raw attributes
    public static volatile SingularAttribute<StockQuant, Integer> id;
    public static volatile SingularAttribute<StockQuant, String> productId;
    public static volatile SingularAttribute<StockQuant, String> productName;
    public static volatile SingularAttribute<StockQuant, BigDecimal> qty;
    public static volatile SingularAttribute<StockQuant, BigDecimal> useQty;
    public static volatile SingularAttribute<StockQuant, String> unit;
    public static volatile SingularAttribute<StockQuant, String> createUid;
    public static volatile SingularAttribute<StockQuant, LocalDateTime> createDate;
    public static volatile SingularAttribute<StockQuant, BigDecimal> cost;
    public static volatile SingularAttribute<StockQuant, Integer> propagatedFromId;
    public static volatile SingularAttribute<StockQuant, Integer> packageId;
    public static volatile SingularAttribute<StockQuant, Integer> locationId;
    public static volatile SingularAttribute<StockQuant, String> location;    
    public static volatile SingularAttribute<StockQuant, Integer> lotId;
    public static volatile SingularAttribute<StockQuant, String> lot;
    public static volatile SingularAttribute<StockQuant, String> lotCata1;
    public static volatile SingularAttribute<StockQuant, String> lotCata2;
    public static volatile SingularAttribute<StockQuant, Integer> reservationId;
    public static volatile SingularAttribute<StockQuant, Integer> packagingTypeId;
    public static volatile SingularAttribute<StockQuant, Integer> negativeMoveId;
    public static volatile SingularAttribute<StockQuant, LocalDateTime> inDate;
}