/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-angular:src/main/java/domain/EntityMeta_.java.e.vm
 */
package com.sadetec.model;

import java.time.LocalDateTime;

import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@StaticMetamodel(SysCompany.class)
public abstract class SysCompany_ {

    // Raw attributes
    public static volatile SingularAttribute<SysCompany, Integer> id;
    public static volatile SingularAttribute<SysCompany, String> name;
    public static volatile SingularAttribute<SysCompany, Integer> partnerId;
    public static volatile SingularAttribute<SysCompany, Integer> sequence;
    public static volatile SingularAttribute<SysCompany, LocalDateTime> createDate;
    public static volatile SingularAttribute<SysCompany, String> email;
    public static volatile SingularAttribute<SysCompany, String> phone;
    public static volatile SingularAttribute<SysCompany, String> companyRegistry;
    public static volatile SingularAttribute<SysCompany, String> enabled;
    public static volatile SingularAttribute<SysCompany, String> remarks;
}