/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-angular:src/main/java/domain/Entity.java.e.vm
 */
package com.sadetec.model;

import static javax.persistence.GenerationType.IDENTITY;

import java.io.Serializable;
import java.time.LocalDateTime;
import java.util.logging.Logger;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.validation.constraints.Digits;
import javax.validation.constraints.Size;

import org.hibernate.validator.constraints.Email;
import org.hibernate.validator.constraints.NotEmpty;

import com.google.common.base.MoreObjects;

@Entity
@Table(name = "sys_company")
public class SysCompany implements Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = Logger.getLogger(SysCompany.class.getName());

    // Raw attributes
    private Integer id;
    private String name;
    private Integer parentId;
    private Integer sequence;
    private LocalDateTime createDate;
    private String email;
    private String phone;
    private String companyRegistry;
    private String enabled;
    private String remarks;

    public String entityClassName() {
        return SysCompany.class.getSimpleName();
    }

    // -- [id] ------------------------

    @Column(name = "id", precision = 10)
    @GeneratedValue(strategy = IDENTITY)
    @Id
    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public SysCompany id(Integer id) {
        setId(id);
        return this;
    }

    @Transient
    public boolean isIdSet() {
        return id != null;
    }
    // -- [name] ------------------------

    /**
     * 部门名
     */
    @NotEmpty
    @Size(max = 100)
    @Column(name = "name", nullable = false, length = 100)
    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public SysCompany name(String name) {
        setName(name);
        return this;
    }
    // -- [partnerId] ------------------------

    /**
     * 上级部门名
     */
    @Digits(integer = 10, fraction = 0)
    @Column(name = "parent_id", precision = 10)
    public Integer getParentId() {
        return parentId;
    }

    public void setParentId(Integer parentId) {
        this.parentId = parentId;
    }

    public SysCompany parentId(Integer parentId) {
    	setParentId(parentId);
        return this;
    }
    // -- [sequence] ------------------------

    /**
     * 序号
     */
    @Digits(integer = 10, fraction = 0)
    @Column(name = "`sequence`", precision = 10)
    public Integer getSequence() {
        return sequence;
    }

    public void setSequence(Integer sequence) {
        this.sequence = sequence;
    }

    public SysCompany sequence(Integer sequence) {
        setSequence(sequence);
        return this;
    }
    // -- [createDate] ------------------------

    /**
     * 创建时间
     */
    @Column(name = "create_date", length = 19)
    public LocalDateTime getCreateDate() {
        return createDate;
    }

    public void setCreateDate(LocalDateTime createDate) {
        this.createDate = createDate;
    }

    public SysCompany createDate(LocalDateTime createDate) {
        setCreateDate(createDate);
        return this;
    }
    // -- [email] ------------------------

    /**
     * 邮件
     */
    @Email
    @Size(max = 200)
    @Column(name = "email", length = 200)
    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public SysCompany email(String email) {
        setEmail(email);
        return this;
    }
    // -- [phone] ------------------------

    /**
     * 电话
     */
    @Size(max = 200)
    @Column(name = "phone", length = 200)
    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public SysCompany phone(String phone) {
        setPhone(phone);
        return this;
    }
    // -- [companyRegistry] ------------------------

    /**
     * 注册地
     */
    @Size(max = 200)
    @Column(name = "company_registry", length = 200)
    public String getCompanyRegistry() {
        return companyRegistry;
    }

    public void setCompanyRegistry(String companyRegistry) {
        this.companyRegistry = companyRegistry;
    }

    public SysCompany companyRegistry(String companyRegistry) {
        setCompanyRegistry(companyRegistry);
        return this;
    }
    // -- [enabled] ------------------------

    /**
     * 是否可用 1：可用 0：停用
     */
    @Column(name = "enabled", length = 1)
    public String getEnabled() {
        return enabled;
    }

    public void setEnabled(String enabled) {
        this.enabled = enabled;
    }

    public SysCompany enabled(String enabled) {
        setEnabled(enabled);
        return this;
    }
    // -- [remarks] ------------------------

    /**
     * 备注
     */
    @Size(max = 255)
    @Column(name = "remarks")
    public String getRemarks() {
        return remarks;
    }

    public void setRemarks(String remarks) {
        this.remarks = remarks;
    }

    public SysCompany remarks(String remarks) {
        setRemarks(remarks);
        return this;
    }

    /**
     * Apply the default values.
     */
    public SysCompany withDefaults() {
        setEnabled("1");
        return this;
    }

    /**
     * Equals implementation using a business key.
     */
    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof SysCompany && hashCode() == other.hashCode());
    }


    /**
     * Construct a readable string representation for this SysCompany instance.
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this) //
                .add("id", getId()) //
                .add("name", getName()) //
                .add("parentId", getParentId()) //
                .add("sequence", getSequence()) //
                .add("createDate", getCreateDate()) //
                .add("email", getEmail()) //
                .add("phone", getPhone()) //
                .add("companyRegistry", getCompanyRegistry()) //
                .add("enabled", getEnabled()) //
                .add("remarks", getRemarks()) //
                .toString();
    }
}