/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-angular:src/main/java/domain/EntityMeta_.java.e.vm
 */
package com.sadetec.model;

import java.time.LocalDateTime;

import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@StaticMetamodel(SysRole.class)
public abstract class SysRole_ {

    // Raw attributes
    public static volatile SingularAttribute<SysRole, Integer> id;
    public static volatile SingularAttribute<SysRole, String> name;
    public static volatile SingularAttribute<SysRole, String> enabled;
    public static volatile SingularAttribute<SysRole, String> remarks;
    public static volatile SingularAttribute<SysRole, LocalDateTime> createDate;
    public static volatile SingularAttribute<SysRole, LocalDateTime> updateDate;
    public static volatile SingularAttribute<SysRole, String> delFlag;
}