/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-angular:src/main/java/domain/EntityMeta_.java.e.vm
 */
package com.sadetec.model;

import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@StaticMetamodel(SysUser.class)
public abstract class SysUser_ {

    // Raw attributes
    public static volatile SingularAttribute<SysUser, Integer> id;
    public static volatile SingularAttribute<SysUser, String> loginName;
    public static volatile SingularAttribute<SysUser, String> password;
    public static volatile SingularAttribute<SysUser, String> name;
    public static volatile SingularAttribute<SysUser, String> email;
    public static volatile SingularAttribute<SysUser, String> phone;
    public static volatile SingularAttribute<SysUser, String> mobile;
    public static volatile SingularAttribute<SysUser, String> enabled;
    public static volatile SingularAttribute<SysUser, String> remarks;
    public static volatile SingularAttribute<SysUser, String> delFlag;
}