/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-angular:src/main/java/domain/CompositePk_.java.cpk.vm
 */
package com.sadetec.model;

import javax.persistence.metamodel.SingularAttribute;
import javax.persistence.metamodel.StaticMetamodel;

@StaticMetamodel(SysUserRolePk.class)
public abstract class SysUserRolePk_ {
    // pk attributes
    public static volatile SingularAttribute<SysUserRolePk, Integer> roleId;
    public static volatile SingularAttribute<SysUserRolePk, Integer> userId;
}
