/*
 * Source code generated by Celerio, a Jaxio product.
 * Documentation: http://www.jaxio.com/documentation/celerio/
 * Follow us on twitter: @jaxiosoft
 * Need commercial support ? Contact us: info@jaxio.com
 * Template pack-angular:src/main/java/domain/Entity.java.e.vm
 */
package com.sadetec.model;

import java.io.Serializable;
import java.util.logging.Logger;

import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;
import javax.persistence.Transient;
import javax.persistence.UniqueConstraint;

import com.google.common.base.MoreObjects;
import com.google.common.base.Objects;

@Entity
@Table(name = "sys_user_role", uniqueConstraints = { @UniqueConstraint(name = "PRIMARY", columnNames = { "user_id", "role_id" }) })
public class SysUserRole implements Serializable {
    private static final long serialVersionUID = 1L;
    private static final Logger log = Logger.getLogger(SysUserRole.class.getName());

    // Composite primary key
    private SysUserRolePk id = new SysUserRolePk();

    public String entityClassName() {
        return SysUserRole.class.getSimpleName();
    }

    // -----------------------
    // Composite Primary Key
    // -----------------------

    /**
     * Returns the composite primary key.
     */
    @EmbeddedId
    public SysUserRolePk getId() {
        return id;
    }

    /**
     * Set the composite primary key.
     * @param id the composite primary key.
     */
    public void setId(SysUserRolePk id) {
        this.id = id;
    }

    public SysUserRole id(SysUserRolePk id) {
        setId(id);
        return this;
    }

    /**
     * Tells whether or not this instance has a non empty composite primary key set.
     * @return true if a non empty primary key is set, false otherwise
     */
    @Transient
    public boolean isIdSet() {
        return getId() != null && getId().areFieldsSet();
    }

    /**
     * Apply the default values.
     */
    public SysUserRole withDefaults() {
        return this;
    }

    /**
     * Equals implementation using a business key.
     */
    @Override
    public boolean equals(Object other) {
        return this == other || (other instanceof SysUserRole && hashCode() == other.hashCode());
    }

    /**
     * Construct a readable string representation for this SysUserRole instance.
     * @see java.lang.Object#toString()
     */
    @Override
    public String toString() {
        return MoreObjects.toStringHelper(this) //
                .toString();
    }
}